# **데이터 불러오기, 저장하기**


---

## **[1] csv 파일**
- 불러오기
 - `데이터변수 = pd.read_csv(파일경로)`
- 저장하기
 - `데이터변수.to_csv(파일경로)`

In [1]:
import pandas as pd

In [12]:
csv_file_path = r"C:\Users\ryang\OneDrive\문서\공부\part.2\data\titanic_train.csv"
csv_data = pd.read_csv(csv_file_path)

In [10]:
csv_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

- `index_col`: 인덱스로 사용할 컬럼
- `usecols`: 사용할 컬럼

In [13]:
csv_data1 = pd.read_csv(csv_file_path, index_col = 0)
csv_data1.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [14]:
csv_data1 = pd.read_csv(csv_file_path, index_col = 'PassengerId', usecols = ['PassengerId','Survived','Pclass','Age'])
csv_data1.head()

             Survived  Pclass   Age
PassengerId
1                   0       3  22.0
2                   1       1  38.0
3                   1       3  26.0
4                   1       1  35.0
5                   0       3  35.0

In [17]:
csv_file_path1 = r'C:\Users\ryang\OneDrive\문서\공부\part.2\data\titanic_train_testt.csv' ## titanic_train_testt.csv 라는 파일이 새로 만들어짐짐
csv_data1.to_csv(csv_file_path1)

In [18]:
pd.read_csv(csv_file_path1).head()

   PassengerId  Survived  Pclass   Age
0            1         0       3  22.0
1            2         1       1  38.0
2            3         1       3  26.0
3            4         1       1  35.0
4            5         0       3  35.0

## **[2] 엑셀 파일**
- 불러오기
 - `데이터변수 = pd.read_excel(파일경로, sheet_name=시트이름)`
- 저장하기
 - `데이터변수.to_excel(파일경로, sheet_name=시트이름)`

In [23]:
excel_file_path = r'C:\Users\ryang\OneDrive\문서\공부\part.2\data\titanic_train.xlsx'
excel_data = pd.read_excel(excel_file_path, sheet_name='시트1')

In [20]:
excel_data.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S

- `header`: 컬럼 이름으로 사용할 행
- `index_col`: 인덱스로 사용할 컬럼
- `usecols`: 사용할 컬럼

In [24]:
excel_data = pd.read_excel(excel_file_path, sheet_name='시트1', header=1)
excel_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [25]:
excel_data1 = pd.read_excel(excel_file_path, sheet_name='시트1', header=1, index_col = 'PassengerId', usecols = ['PassengerId','Survived','Pclass','Age'])
excel_data1.head()

             Survived  Pclass   Age
PassengerId
1                   0       3  22.0
2                   1       1  38.0
3                   1       3  26.0
4                   1       1  35.0
5                   0       3  35.0

In [27]:
excel_file_path1 = r'C:\Users\ryang\OneDrive\문서\공부\part.2\data\titanic_train_testt.xlsx'
excel_data1.to_excel(excel_file_path1, sheet_name = 'sheet1')

In [28]:
pd.read_excel(excel_file_path1, sheet_name='sheet1').head()

   PassengerId  Survived  Pclass   Age
0            1         0       3  22.0
1            2         1       1  38.0
2            3         1       3  26.0
3            4         1       1  35.0
4            5         0       3  35.0

## **[3] 웹 html 파일**
- `pd.read_html(html경로)`
- `encoding`: 한글이 깨져서 나올 때 `utf-8/cp949`로 설정합니다.

In [1]:
pip install lxml

Collecting lxml
  Downloading lxml-5.4.0-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-5.4.0-cp313-cp313-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   --------------------------- ------------ 2.6/3.8 MB 13.5 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 12.7 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-5.4.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install html5lib

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\users\1\appdata\local\programs\python\python313\lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\1\appdata\local\programs\python\python313\lib\site-packages (from html5lib) (0.5.1)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: html5lib
Successfully installed html5lib-1.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\1\appdata\local\programs\python\python313\lib\site-packages (4.13.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\1\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\1\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4) (4.13.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [35]:
html_path = 'https://finance.naver.com/sise/sise_quant.naver'

quant_data_list = pd.read_html(html_path)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 94: invalid start byte

In [40]:
quant_data_list

[     0      1          2        3          4       5
 0  거래량   매수호가   거래대금(백만)  시가총액(억)    영업이익(억)  PER(배)
 1   시가   매도호가      전일거래량  자산총계(억)    영업이익증가율  ROE(%)
 2   고가  매수총잔량      외국인비율  부채총계(억)   당기순이익(억)  ROA(%)
 3   저가  매도총잔량  상장주식수(천주)   매출액(억)   주당순이익(원)  PBR(배)
 4  NaN    NaN        NaN   매출액증가율  보통주배당금(원)  유보율(%),
          N                 종목명      현재가      전일비     등락률          거래량  \
 0      NaN                 NaN      NaN      NaN     NaN          NaN
 1      1.0    KODEX 200선물인버스2X   2185.0   하락  50  -2.24%  124732196.0
 2      2.0                동양철관   1460.0  하락  146  -9.09%   34312901.0
 3      3.0                대한제당   3865.0   상승  15  +0.39%   30286930.0
 4      4.0    KODEX 코스닥150레버리지   7185.0   상승  25  +0.35%   26637087.0
 ..     ...                 ...      ...      ...     ...          ...
 156   99.0  KODEX 200타겟위클리커버드콜   9415.0   상승  75  +0.80%    1067187.0
 157  100.0     KODEX 미국휴머노이드로봇  10330.0  상승  565  +5.79%    1066467.0
 158    NaN                 NaN      NaN      NaN     NaN          NaN
 159    NaN                 NaN      NaN      NaN     NaN          NaN
 160    NaN                 NaN      NaN      NaN     NaN          NaN

          거래대금     매수호가     매도호가     시가총액    PER    ROE
 0         NaN      NaN      NaN      NaN    NaN    NaN
 1    272258.0   2185.0   2190.0  10464.0    NaN    NaN
 2     52607.0   1460.0   1461.0   2319.0 -10.21 -20.13
 3    121971.0   3865.0   3875.0   3467.0  18.15   3.68
 4    192233.0   7180.0   7185.0  19486.0    NaN    NaN
 ..        ...      ...      ...      ...    ...    ...
 156   10052.0   9415.0   9420.0   3728.0    NaN    NaN
 157   11008.0  10315.0  10330.0    310.0    NaN    NaN
 158       NaN      NaN      NaN      NaN    NaN    NaN
 159       NaN      NaN      NaN      NaN    NaN    NaN
 160       NaN      NaN      NaN      NaN    NaN    NaN

 [161 rows x 12 columns]]

In [37]:
quant_data_list = pd.read_html(html_path, encoding='cp949')
quant_data_list

c:\Users\ryang\AppData\Local\Programs\Python\Python313\Lib\site-packages\bs4\__init__.py:339: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn(

[     0      1          2        3          4       5
 0  거래량   매수호가   거래대금(백만)  시가총액(억)    영업이익(억)  PER(배)
 1   시가   매도호가      전일거래량  자산총계(억)    영업이익증가율  ROE(%)
 2   고가  매수총잔량      외국인비율  부채총계(억)   당기순이익(억)  ROA(%)
 3   저가  매도총잔량  상장주식수(천주)   매출액(억)   주당순이익(원)  PBR(배)
 4  NaN    NaN        NaN   매출액증가율  보통주배당금(원)  유보율(%),
          N                 종목명      현재가      전일비     등락률          거래량  \
 0      NaN                 NaN      NaN      NaN     NaN          NaN
 1      1.0    KODEX 200선물인버스2X   2185.0   하락  50  -2.24%  124732196.0
 2      2.0                동양철관   1460.0  하락  146  -9.09%   34312901.0
 3      3.0                대한제당   3865.0   상승  15  +0.39%   30286930.0
 4      4.0    KODEX 코스닥150레버리지   7185.0   상승  25  +0.35%   26637087.0
 ..     ...                 ...      ...      ...     ...          ...
 156   99.0  KODEX 200타겟위클리커버드콜   9415.0   상승  75  +0.80%    1067187.0
 157  100.0     KODEX 미국휴머노이드로봇  10330.0  상승  565  +5.79%    1066467.0
 158    NaN                 NaN      NaN      NaN     NaN          NaN
 159    NaN                 NaN      NaN      NaN     NaN          NaN
 160    NaN                 NaN      NaN      NaN     NaN          NaN

          거래대금     매수호가     매도호가     시가총액    PER    ROE
 0         NaN      NaN      NaN      NaN    NaN    NaN
 1    272258.0   2185.0   2190.0  10464.0    NaN    NaN
 2     52607.0   1460.0   1461.0   2319.0 -10.21 -20.13
 3    121971.0   3865.0   3875.0   3467.0  18.15   3.68
 4    192233.0   7180.0   7185.0  19486.0    NaN    NaN
 ..        ...      ...      ...      ...    ...    ...
 156   10052.0   9415.0   9420.0   3728.0    NaN    NaN
 157   11008.0  10315.0  10330.0    310.0    NaN    NaN
 158       NaN      NaN      NaN      NaN    NaN    NaN
 159       NaN      NaN      NaN      NaN    NaN    NaN
 160       NaN      NaN      NaN      NaN    NaN    NaN

 [161 rows x 12 columns]]

In [ ]:
kospi = quant_data_list[1]  ## 이게 더 이쁘게 나온 이유 - 네이버 금융 페이지에는 여러 개의 표가 있고,
## quant_data_list[0]은 그냥 "빈 칸 + 설명 + 광고 + 로그인" 같은 쓰레기 테이블이었고
##quant_data_list[1]이 우리가 원하는 실제 주식 데이터 표였던 거야!

In [39]:
kospi

,N,종목명,현재가,전일비,등락률,거래량,거래대금,매수호가,매도호가,시가총액,PER,ROE
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,KODEX 200선물인버스2X,2185.0,하락 50,-2.24%,124732196.0,272258.0,2185.0,2190.0,10464.0,NaN,NaN
2,2.0,동양철관,1460.0,하락 146,-9.09%,34312901.0,52607.0,1460.0,1461.0,2319.0,-10.21,-20.13
3,3.0,대한제당,3865.0,상승 15,+0.39%,30286930.0,121971.0,3865.0,3875.0,3467.0,18.15,3.68
4,4.0,KODEX 코스닥150레버리지,7185.0,상승 25,+0.35%,26637087.0,192233.0,7180.0,7185.0,19486.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
156,99.0,KODEX 200타겟위클리커버드콜,9415.0,상승 75,+0.80%,1067187.0,10052.0,9415.0,9420.0,3728.0,NaN,NaN
157,100.0,KODEX 미국휴머노이드로봇,10330.0,상승 565,+5.79%,1066467.0,11008.0,10315.0,10330.0,310.0,NaN,NaN
158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
kospi.dropna(how='all').reset_index(drop=True) ## null값 삭제

,N,종목명,현재가,전일비,등락률,거래량,거래대금,매수호가,매도호가,시가총액,PER,ROE
0,1.0,KODEX 200선물인버스2X,2185.0,하락 50,-2.24%,124732196.0,272258.0,2185.0,2190.0,10464.0,NaN,NaN
1,2.0,동양철관,1460.0,하락 146,-9.09%,34312901.0,52607.0,1460.0,1461.0,2319.0,-10.21,-20.13
2,3.0,대한제당,3865.0,상승 15,+0.39%,30286930.0,121971.0,3865.0,3875.0,3467.0,18.15,3.68
3,4.0,KODEX 코스닥150레버리지,7185.0,상승 25,+0.35%,26637087.0,192233.0,7180.0,7185.0,19486.0,NaN,NaN
4,5.0,KODEX 레버리지,15365.0,상승 285,+1.89%,24322206.0,374602.0,15365.0,15370.0,27496.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96.0,YG PLUS,5250.0,상승 210,+4.17%,1115742.0,5839.0,5240.0,5250.0,3330.0,276.32,0.73
96,97.0,TIGER 차이나전기차SOLACTIVE,9560.0,상승 135,+1.43%,1088836.0,10414.0,9555.0,9560.0,16673.0,NaN,NaN
97,98.0,에이프로젠,740.0,상승 3,+0.41%,1075834.0,799.0,740.0,741.0,2308.0,-3.56,-37.91
98,99.0,KODEX 200타겟위클리커버드콜,9415.0,상승 75,+0.80%,1067187.0,10052.0,9415.0,9420.0,3728.0,NaN,NaN
99,100.0,KODEX 미국휴머노이드로봇,10330.0,상승 565,+5.79%,1066467.0,11008.0,10315.0,10330.0,310.0,NaN,NaN