# **인덱스, 행, 열**


---

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [3]:
import pandas as pd

file_path = r'./data/titanic_train.csv'
df = pd.read_csv(file_path)

## **[1] 인덱스**
- 인덱스란 데이터프레임 행들의 이름입니다.

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.index ## 0부터 시작해서 891에서 끝나고 인덱스는 1씩 증가한다.

RangeIndex(start=0, stop=891, step=1)

In [6]:
print(list(df.index))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890]

### **인덱스 변경**
- 인덱스 몇개를 바꿀 때
    - `데이터명.rename({인덱스:바꿀 인덱스, 인덱스:바꿀 인덱스, ...})`
- 인덱스 전체를 바꿀 때
    - `데이터명.index = 바꿀 인덱스 리스트`

In [7]:
df1 = df.copy()
df1.rename({0:'row1', 1:'row2'})

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
row1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
row2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [8]:
df1.head() #rename은 데이터프레임을 바꾸어주지 않으므로 변경을 하려면 다시 덧씌워주어야 합니다.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
df1 = df1.rename({0:'row1', 1:'row2'})
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
row1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
row2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df1.index = [i+1 for i in range(len(df1))] ## 인덱스를 1부터 시작하게 바꿔줍니다.
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### **열을 인덱스로 설정**
- `데이터명.set_index(컬럼명)`

In [ ]:
df1.set_index('PassengerId') ## PassengerId를 인덱스로 바꿔줍니다.

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [12]:
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
df1 = df1.set_index('PassengerId') #마찬가지로 변경을 하려면 덧씌워주어야 합니다.
df1.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### **인덱스를 열로 변환**
- 인덱스를 열로 변환하고 그 열을 남기고 싶으면
    - `데이터명.reset_index()`
- 인덱스를 열로 변환하고 그 열을 삭제하고 싶으면
    - `데이터명.reset_index(drop = True)`

In [14]:
df1.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
df1.reset_index()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [16]:
df1.reset_index(drop=True)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
df1 = df1.reset_index()
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## **[2] 행**

### **행의 추가/제거**
- 행의 추가
    - `pd.concat([기존 데이터명, 붙일 데이터명])`
- 행의 제거
    - `데이터명.drop(인덱스명, axis=0)`

In [18]:
df1 = df.copy()
df2 = df.copy()

df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [19]:
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [20]:
df3 = pd.concat([df1, df2])
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df3 = df3.reset_index(drop=True) ## 인덱스를 초기화합니다.
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1777,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
1778,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
1779,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
1780,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
1781,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [22]:
df3.drop([i for i in range(891, len(df3))])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### 행 중복 제거
- `데이터명.drop_duplicates()`

In [23]:
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1777,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
1778,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
1779,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
1780,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
1781,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df3.drop_duplicates()  # 중복된 행을 제거합니다.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## **[3] 열**

### **열의 추가/제거**

- 열의 추가
    - `데이터명[추가할 컬럼명] = 추가할 값`
- 열의 제거
    - `데이터명.drop(제거할 컬럼명, axis=1)`  ## axis=1 은 고정. 기본적으로 axis가 0으로 설정되어 있기때문에 바꿔줘야 함.

In [25]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df1 = df.copy()
df1['age_simplified'] = df1['Age']//10 * 10 ## 나잇대 구분. 10대, 20대 ...

In [27]:
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_simplified
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,20.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,30.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,20.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,30.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,30.0

In [28]:
print(list(df1['Name'].str.split(','))) #문자열 컬럼에 str.split()을 쓰면 특정 문자열을 기준으로 자를 수 있습니다.

[['Braund', ' Mr. Owen Harris'], ['Cumings', ' Mrs. John Bradley (Florence Briggs Thayer)'], ['Heikkinen', ' Miss. Laina'], ['Futrelle', ' Mrs. Jacques Heath (Lily May Peel)'], ['Allen', ' Mr. William Henry'], ['Moran', ' Mr. James'], ['McCarthy', ' Mr. Timothy J'], ['Palsson', ' Master. Gosta Leonard'], ['Johnson', ' Mrs. Oscar W (Elisabeth Vilhelmina Berg)'], ['Nasser', ' Mrs. Nicholas (Adele Achem)'], ['Sandstrom', ' Miss. Marguerite Rut'], ['Bonnell', ' Miss. Elizabeth'], ['Saundercock', ' Mr. William Henry'], ['Andersson', ' Mr. Anders Johan'], ['Vestrom', ' Miss. Hulda Amanda Adolfina'], ['Hewlett', ' Mrs. (Mary D Kingcome) '], ['Rice', ' Master. Eugene'], ['Williams', ' Mr. Charles Eugene'], ['Vander Planke', ' Mrs. Julius (Emelia Maria Vandemoortele)'], ['Masselmani', ' Mrs. Fatima'], ['Fynney', ' Mr. Joseph J'], ['Beesley', ' Mr. Lawrence'], ['McGowan', ' Miss. Anna "Annie"'], ['Sloper', ' Mr. William Thompson'], ['Palsson', ' Miss. Torborg Danira'], ['Asplund', ' Mrs. Carl Oscar (Selma Augusta Emilia Johansson)'], ['Emir', ' Mr. Farred Chehab'], ['Fortune', ' Mr. Charles Alexander'], ["O'Dwyer", ' Miss. Ellen "Nellie"'], ['Todoroff', ' Mr. Lalio'], ['Uruchurtu', ' Don. Manuel E'], ['Spencer', ' Mrs. William Augustus (Marie Eugenie)'], ['Glynn', ' Miss. Mary Agatha'], ['Wheadon', ' Mr. Edward H'], ['Meyer', ' Mr. Edgar Joseph'], ['Holverson', ' Mr. Alexander Oskar'], ['Mamee', ' Mr. Hanna'], ['Cann', ' Mr. Ernest Charles'], ['Vander Planke', ' Miss. Augusta Maria'], ['Nicola-Yarred', ' Miss. Jamila'], ['Ahlin', ' Mrs. Johan (Johanna Persdotter Larsson)'], ['Turpin', ' Mrs. William John Robert (Dorothy Ann Wonnacott)'], ['Kraeff', ' Mr. Theodor'], ['Laroche', ' Miss. Simonne Marie Anne Andree'], ['Devaney', ' Miss. Margaret Delia'], ['Rogers', ' Mr. William John'], ['Lennon', ' Mr. Denis'], ["O'Driscoll", ' Miss. Bridget'], ['Samaan', ' Mr. Youssef'], ['Arnold-Franchi', ' Mrs. Josef (Josefine Franchi)'], ['Panula', ' Master. Juha Niilo'], ['Nosworthy', ' Mr. Richard Cater'], ['Harper', ' Mrs. Henry Sleeper (Myna Haxtun)'], ['Faunthorpe', ' Mrs. Lizzie (Elizabeth Anne Wilkinson)'], ['Ostby', ' Mr. Engelhart Cornelius'], ['Woolner', ' Mr. Hugh'], ['Rugg', ' Miss. Emily'], ['Novel', ' Mr. Mansouer'], ['West', ' Miss. Constance Mirium'], ['Goodwin', ' Master. William Frederick'], ['Sirayanian', ' Mr. Orsen'], ['Icard', ' Miss. Amelie'], ['Harris', ' Mr. Henry Birkhardt'], ['Skoog', ' Master. Harald'], ['Stewart', ' Mr. Albert A'], ['Moubarek', ' Master. Gerios'], ['Nye', ' Mrs. (Elizabeth Ramell)'], ['Crease', ' Mr. Ernest James'], ['Andersson', ' Miss. Erna Alexandra'], ['Kink', ' Mr. Vincenz'], ['Jenkin', ' Mr. Stephen Curnow'], ['Goodwin', ' Miss. Lillian Amy'], ['Hood', ' Mr. Ambrose Jr'], ['Chronopoulos', ' Mr. Apostolos'], ['Bing', ' Mr. Lee'], ['Moen', ' Mr. Sigurd Hansen'], ['Staneff', ' Mr. Ivan'], ['Moutal', ' Mr. Rahamin Haim'], ['Caldwell', ' Master. Alden Gates'], ['Dowdell', ' Miss. Elizabeth'], ['Waelens', ' Mr. Achille'], ['Sheerlinck', ' Mr. Jan Baptist'], ['McDermott', ' Miss. Brigdet Delia'], ['Carrau', ' Mr. Francisco M'], ['Ilett', ' Miss. Bertha'], ['Backstrom', ' Mrs. Karl Alfred (Maria Mathilda Gustafsson)'], ['Ford', ' Mr. William Neal'], ['Slocovski', ' Mr. Selman Francis'], ['Fortune', ' Miss. Mabel Helen'], ['Celotti', ' Mr. Francesco'], ['Christmann', ' Mr. Emil'], ['Andreasson', ' Mr. Paul Edvin'], ['Chaffee', ' Mr. Herbert Fuller'], ['Dean', ' Mr. Bertram Frank'], ['Coxon', ' Mr. Daniel'], ['Shorney', ' Mr. Charles Joseph'], ['Goldschmidt', ' Mr. George B'], ['Greenfield', ' Mr. William Bertram'], ['Doling', ' Mrs. John T (Ada Julia Bone)'], ['Kantor', ' Mr. Sinai'], ['Petranec', ' Miss. Matilda'], ['Petroff', ' Mr. Pastcho ("Pentcho")'], ['White', ' Mr. Richard Frasar'], ['Johansson', ' Mr. Gustaf Joel'], ['Gustafsson', ' Mr. Anders Vilhelm'], ['Mionoff', ' Mr. Stoytcho'], ['Salkjelsvik', ' Miss. Anna Kristine'], ['Moss', ' Mr. Albert Johan'], ['Rekic', ' Mr. Tido'], ['Moran', ' Miss. Bertha'], ['Porter', ' Mr. Walter Chamberlain'], ['Zabour', ' Miss. Hileni'], ['Barton', ' Mr. David John'], ['Jussila', ' Miss. Katriina'], ['Attalah', ' Miss. Malake'], ['Pekoniemi', ' Mr. Edvard'], ['Connors', ' Mr. Patrick'], ['Turpin', ' Mr. William John Robert'], ['Baxter', ' Mr. Quigg Edmond'], ['Andersson', ' Miss. Ellis Anna Maria'], ['Hickman', ' Mr. Stanley George'], ['Moore', ' Mr. Leonard Charles'], ['Nasser', ' Mr. Nicholas'], ['Webber', ' Miss. Susan'], ['White', ' Mr. Percival Wayland'], ['Nicola-Yarred', ' Master. Elias'], ['McMahon', ' Mr. Martin'], ['Madsen', ' Mr. Fridtjof Arne'], ['Peter', ' Miss. Anna'], ['Ekstrom', ' Mr. Johan'], ['Drazenoic', ' Mr. Jozef'], ['Coelho', ' Mr. Domingos Fernandeo'], ['Robins', ' Mrs. Alexander A (Grace Charity Laury)'], ['Weisz', ' Mrs. Leopold (Mathilde Francoise Pede)'], ['Sobey', ' Mr. Samuel James Hayden'], ['Richard', ' Mr. Emile'], ['Newsom', ' Miss. Helen Monypeny'], ['Futrelle', ' Mr. Jacques Heath'], ['Osen', ' Mr. Olaf Elon'], ['Giglio', ' Mr. Victor'], ['Boulos', ' Mrs. Joseph (Sultana)'], ['Nysten', ' Miss. Anna Sofia'], ['Hakkarainen', ' Mrs. Pekka Pietari (Elin Matilda Dolck)'], ['Burke', ' Mr. Jeremiah'], ['Andrew', ' Mr. Edgardo Samuel'], ['Nicholls', ' Mr. Joseph Charles'], ['Andersson', ' Mr. August Edvard ("Wennerstrom")'], ['Ford', ' Miss. Robina Maggie "Ruby"'], ['Navratil', ' Mr. Michel ("Louis M Hoffman")'], ['Byles', ' Rev. Thomas Roussel Davids'], ['Bateman', ' Rev. Robert James'], ['Pears', ' Mrs. Thomas (Edith Wearne)'], ['Meo', ' Mr. Alfonzo'], ['van Billiard', ' Mr. Austin Blyler'], ['Olsen', ' Mr. Ole Martin'], ['Williams', ' Mr. Charles Duane'], ['Gilnagh', ' Miss. Katherine "Katie"'], ['Corn', ' Mr. Harry'], ['Smiljanic', ' Mr. Mile'], ['Sage', ' Master. Thomas Henry'], ['Cribb', ' Mr. John Hatfield'], ['Watt', ' Mrs. James (Elizabeth "Bessie" Inglis Milne)'], ['Bengtsson', ' Mr. John Viktor'], ['Calic', ' Mr. Jovo'], ['Panula', ' Master. Eino Viljami'], ['Goldsmith', ' Master. Frank John William "Frankie"'], ['Chibnall', ' Mrs. (Edith Martha Bowerman)'], ['Skoog', ' Mrs. William (Anna Bernhardina Karlsson)'], ['Baumann', ' Mr. John D'], ['Ling', ' Mr. Lee'], ['Van der hoef', ' Mr. Wyckoff'], ['Rice', ' Master. Arthur'], ['Johnson', ' Miss. Eleanor Ileen'], ['Sivola', ' Mr. Antti Wilhelm'], ['Smith', ' Mr. James Clinch'], ['Klasen', ' Mr. Klas Albin'], ['Lefebre', ' Master. Henry Forbes'], ['Isham', ' Miss. Ann Elizabeth'], ['Hale', ' Mr. Reginald'], ['Leonard', ' Mr. Lionel'], ['Sage', ' Miss. Constance Gladys'], ['Pernot', ' Mr. Rene'], ['Asplund', ' Master. Clarence Gustaf Hugo'], ['Becker', ' Master. Richard F'], ['Kink-Heilmann', ' Miss. Luise Gretchen'], ['Rood', ' Mr. Hugh Roscoe'], ["O'Brien", ' Mrs. Thomas (Johanna "Hannah" Godfrey)'], ['Romaine', ' Mr. Charles Hallace ("Mr C Rolmane")'], ['Bourke', ' Mr. John'], ['Turcin', ' Mr. Stjepan'], ['Pinsky', ' Mrs. (Rosa)'], ['Carbines', ' Mr. William'], ['Andersen-Jensen', ' Miss. Carla Christine Nielsine'], ['Navratil', ' Master. Michel M'], ['Brown', ' Mrs. James Joseph (Margaret Tobin)'], ['Lurette', ' Miss. Elise'], ['Mernagh', ' Mr. Robert'], ['Olsen', ' Mr. Karl Siegwart Andreas'], ['Madigan', ' Miss. Margaret "Maggie"'], ['Yrois', ' Miss. Henriette ("Mrs Harbeck")'], ['Vande Walle', ' Mr. Nestor Cyriel'], ['Sage', ' Mr. Frederick'], ['Johanson', ' Mr. Jakob Alfred'], ['Youseff', ' Mr. Gerious'], ['Cohen', ' Mr. Gurshon "Gus"'], ['Strom', ' Miss. Telma Matilda'], ['Backstrom', ' Mr. Karl Alfred'], ['Albimona', ' Mr. Nassef Cassem'], ['Carr', ' Miss. Helen "Ellen"'], ['Blank', ' Mr. Henry'], ['Ali', ' Mr. Ahmed'], ['Cameron', ' Miss. Clear Annie'], ['Perkin', ' Mr. John Henry'], ['Givard', ' Mr. Hans Kristensen'], ['Kiernan', ' Mr. Philip'], ['Newell', ' Miss. Madeleine'], ['Honkanen', ' Miss. Eliina'], ['Jacobsohn', ' Mr. Sidney Samuel'], ['Bazzani', ' Miss. Albina'], ['Harris', ' Mr. Walter'], ['Sunderland', ' Mr. Victor Francis'], ['Bracken', ' Mr. James H'], ['Green', ' Mr. George Henry'], ['Nenkoff', ' Mr. Christo'], ['Hoyt', ' Mr. Frederick Maxfield'], ['Berglund', ' Mr. Karl Ivar Sven'], ['Mellors', ' Mr. William John'], ['Lovell', ' Mr. John Hall ("Henry")'], ['Fahlstrom', ' Mr. Arne Jonas'], ['Lefebre', ' Miss. Mathilde'], ['Harris', ' Mrs. Henry Birkhardt (Irene Wallach)'], ['Larsson', ' Mr. Bengt Edvin'], ['Sjostedt', ' Mr. Ernst Adolf'], ['Asplund', ' Miss. Lillian Gertrud'], ['Leyson', ' Mr. Robert William Norman'], ['Harknett', ' Miss. Alice Phoebe'], ['Hold', ' Mr. Stephen'], ['Collyer', ' Miss. Marjorie "Lottie"'], ['Pengelly', ' Mr. Frederick William'], ['Hunt', ' Mr. George Henry'], ['Zabour', ' Miss. Thamine'], ['Murphy', ' Miss. Katherine "Kate"'], ['Coleridge', ' Mr. Reginald Charles'], ['Maenpaa', ' Mr. Matti Alexanteri'], ['Attalah', ' Mr. Sleiman'], ['Minahan', ' Dr. William Edward'], ['Lindahl', ' Miss. Agda Thorilda Viktoria'], ['Hamalainen', ' Mrs. William (Anna)'], ['Beckwith', ' Mr. Richard Leonard'], ['Carter', ' Rev. Ernest Courtenay'], ['Reed', ' Mr. James George'], ['Strom', ' Mrs. Wilhelm (Elna Matilda Persson)'], ['Stead', ' Mr. William Thomas'], ['Lobb', ' Mr. William Arthur'], ['Rosblom', ' Mrs. Viktor (Helena Wilhelmina)'], ['Touma', ' Mrs. Darwis (Hanne Youssef Razi)'], ['Thorne', ' Mrs. Gertrude Maybelle'], ['Cherry', ' Miss. Gladys'], ['Ward', ' Miss. Anna'], ['Parrish', ' Mrs. (Lutie Davis)'], ['Smith', ' Mr. Thomas'], ['Asplund', ' Master. Edvin Rojj Felix'], ['Taussig', ' Mr. Emil'], ['Harrison', ' Mr. William'], ['Henry', ' Miss. Delia'], ['Reeves', ' Mr. David'], ['Panula', ' Mr. Ernesti Arvid'], ['Persson', ' Mr. Ernst Ulrik'], ['Graham', ' Mrs. William Thompson (Edith Junkins)'], ['Bissette', ' Miss. Amelia'], ['Cairns', ' Mr. Alexander'], ['Tornquist', ' Mr. William Henry'], ['Mellinger', ' Mrs. (Elizabeth Anne Maidment)'], ['Natsch', ' Mr. Charles H'], ['Healy', ' Miss. Hanora "Nora"'], ['Andrews', ' Miss. Kornelia Theodosia'], ['Lindblom', ' Miss. Augusta Charlotta'], ['Parkes', ' Mr. Francis "Frank"'], ['Rice', ' Master. Eric'], ['Abbott', ' Mrs. Stanton (Rosa Hunt)'], ['Duane', ' Mr. Frank'], ['Olsson', ' Mr. Nils Johan Goransson'], ['de Pelsmaeker', ' Mr. Alfons'], ['Dorking', ' Mr. Edward Arthur'], ['Smith', ' Mr. Richard William'], ['Stankovic', ' Mr. Ivan'], ['de Mulder', ' Mr. Theodore'], ['Naidenoff', ' Mr. Penko'], ['Hosono', ' Mr. Masabumi'], ['Connolly', ' Miss. Kate'], ['Barber', ' Miss. Ellen "Nellie"'], ['Bishop', ' Mrs. Dickinson H (Helen Walton)'], ['Levy', ' Mr. Rene Jacques'], ['Haas', ' Miss. Aloisia'], ['Mineff', ' Mr. Ivan'], ['Lewy', ' Mr. Ervin G'], ['Hanna', ' Mr. Mansour'], ['Allison', ' Miss. Helen Loraine'], ['Saalfeld', ' Mr. Adolphe'], ['Baxter', ' Mrs. James (Helene DeLaudeniere Chaput)'], ['Kelly', ' Miss. Anna Katherine "Annie Kate"'], ['McCoy', ' Mr. Bernard'], ['Johnson', ' Mr. William Cahoone Jr'], ['Keane', ' Miss. Nora A'], ['Williams', ' Mr. Howard Hugh "Harry"'], ['Allison', ' Master. Hudson Trevor'], ['Fleming', ' Miss. Margaret'], ['Penasco y Castellana', ' Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)'], ['Abelson', ' Mr. Samuel'], ['Francatelli', ' Miss. Laura Mabel'], ['Hays', ' Miss. Margaret Bechstein'], ['Ryerson', ' Miss. Emily Borie'], ['Lahtinen', ' Mrs. William (Anna Sylfven)'], ['Hendekovic', ' Mr. Ignjac'], ['Hart', ' Mr. Benjamin'], ['Nilsson', ' Miss. Helmina Josefina'], ['Kantor', ' Mrs. Sinai (Miriam Sternin)'], ['Moraweck', ' Dr. Ernest'], ['Wick', ' Miss. Mary Natalie'], ['Spedden', ' Mrs. Frederic Oakley (Margaretta Corning Stone)'], ['Dennis', ' Mr. Samuel'], ['Danoff', ' Mr. Yoto'], ['Slayter', ' Miss. Hilda Mary'], ['Caldwell', ' Mrs. Albert Francis (Sylvia Mae Harbaugh)'], ['Sage', ' Mr. George John Jr'], ['Young', ' Miss. Marie Grice'], ['Nysveen', ' Mr. Johan Hansen'], ['Ball', ' Mrs. (Ada E Hall)'], ['Goldsmith', ' Mrs. Frank John (Emily Alice Brown)'], ['Hippach', ' Miss. Jean Gertrude'], ['McCoy', ' Miss. Agnes'], ['Partner', ' Mr. Austen'], ['Graham', ' Mr. George Edward'], ['Vander Planke', ' Mr. Leo Edmondus'], ['Frauenthal', ' Mrs. Henry William (Clara Heinsheimer)'], ['Denkoff', ' Mr. Mitto'], ['Pears', ' Mr. Thomas Clinton'], ['Burns', ' Miss. Elizabeth Margaret'], ['Dahl', ' Mr. Karl Edwart'], ['Blackwell', ' Mr. Stephen Weart'], ['Navratil', ' Master. Edmond Roger'], ['Fortune', ' Miss. Alice Elizabeth'], ['Collander', ' Mr. Erik Gustaf'], ['Sedgwick', ' Mr. Charles Frederick Waddington'], ['Fox', ' Mr. Stanley Hubert'], ['Brown', ' Miss. Amelia "Mildred"'], ['Smith', ' Miss. Marion Elsie'], ['Davison', ' Mrs. Thomas Henry (Mary E Finck)'], ['Coutts', ' Master. William Loch "William"'], ['Dimic', ' Mr. Jovan'], ['Odahl', ' Mr. Nils Martin'], ['Williams-Lambert', ' Mr. Fletcher Fellows'], ['Elias', ' Mr. Tannous'], ['Arnold-Franchi', ' Mr. Josef'], ['Yousif', ' Mr. Wazli'], ['Vanden Steen', ' Mr. Leo Peter'], ['Bowerman', ' Miss. Elsie Edith'], ['Funk', ' Miss. Annie Clemmer'], ['McGovern', ' Miss. Mary'], ['Mockler', ' Miss. Helen Mary "Ellie"'], ['Skoog', ' Mr. Wilhelm'], ['del Carlo', ' Mr. Sebastiano'], ['Barbara', ' Mrs. (Catherine David)'], ['Asim', ' Mr. Adola'], ["O'Brien", ' Mr. Thomas'], ['Adahl', ' Mr. Mauritz Nils Martin'], ['Warren', ' Mrs. Frank Manley (Anna Sophia Atkinson)'], ['Moussa', ' Mrs. (Mantoura Boulos)'], ['Jermyn', ' Miss. Annie'], ['Aubart', ' Mme. Leontine Pauline'], ['Harder', ' Mr. George Achilles'], ['Wiklund', ' Mr. Jakob Alfred'], ['Beavan', ' Mr. William Thomas'], ['Ringhini', ' Mr. Sante'], ['Palsson', ' Miss. Stina Viola'], ['Meyer', ' Mrs. Edgar Joseph (Leila Saks)'], ['Landergren', ' Miss. Aurora Adelia'], ['Widener', ' Mr. Harry Elkins'], ['Betros', ' Mr. Tannous'], ['Gustafsson', ' Mr. Karl Gideon'], ['Bidois', ' Miss. Rosalie'], ['Nakid', ' Miss. Maria ("Mary")'], ['Tikkanen', ' Mr. Juho'], ['Holverson', ' Mrs. Alexander Oskar (Mary Aline Towner)'], ['Plotcharsky', ' Mr. Vasil'], ['Davies', ' Mr. Charles Henry'], ['Goodwin', ' Master. Sidney Leonard'], ['Buss', ' Miss. Kate'], ['Sadlier', ' Mr. Matthew'], ['Lehmann', ' Miss. Bertha'], ['Carter', ' Mr. William Ernest'], ['Jansson', ' Mr. Carl Olof'], ['Gustafsson', ' Mr. Johan Birger'], ['Newell', ' Miss. Marjorie'], ['Sandstrom', ' Mrs. Hjalmar (Agnes Charlotta Bengtsson)'], ['Johansson', ' Mr. Erik'], ['Olsson', ' Miss. Elina'], ['McKane', ' Mr. Peter David'], ['Pain', ' Dr. Alfred'], ['Trout', ' Mrs. William H (Jessie L)'], ['Niskanen', ' Mr. Juha'], ['Adams', ' Mr. John'], ['Jussila', ' Miss. Mari Aina'], ['Hakkarainen', ' Mr. Pekka Pietari'], ['Oreskovic', ' Miss. Marija'], ['Gale', ' Mr. Shadrach'], ['Widegren', ' Mr. Carl/Charles Peter'], ['Richards', ' Master. William Rowe'], ['Birkeland', ' Mr. Hans Martin Monsen'], ['Lefebre', ' Miss. Ida'], ['Sdycoff', ' Mr. Todor'], ['Hart', ' Mr. Henry'], ['Minahan', ' Miss. Daisy E'], ['Cunningham', ' Mr. Alfred Fleming'], ['Sundman', ' Mr. Johan Julian'], ['Meek', ' Mrs. Thomas (Annie Louise Rowley)'], ['Drew', ' Mrs. James Vivian (Lulu Thorne Christian)'], ['Silven', ' Miss. Lyyli Karoliina'], ['Matthews', ' Mr. William John'], ['Van Impe', ' Miss. Catharina'], ['Gheorgheff', ' Mr. Stanio'], ['Charters', ' Mr. David'], ['Zimmerman', ' Mr. Leo'], ['Danbom', ' Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)'], ['Rosblom', ' Mr. Viktor Richard'], ['Wiseman', ' Mr. Phillippe'], ['Clarke', ' Mrs. Charles V (Ada Maria Winfield)'], ['Phillips', ' Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")'], ['Flynn', ' Mr. James'], ['Pickard', ' Mr. Berk (Berk Trembisky)'], ['Bjornstrom-Steffansson', ' Mr. Mauritz Hakan'], ['Thorneycroft', ' Mrs. Percival (Florence Kate White)'], ['Louch', ' Mrs. Charles Alexander (Alice Adelaide Slow)'], ['Kallio', ' Mr. Nikolai Erland'], ['Silvey', ' Mr. William Baird'], ['Carter', ' Miss. Lucile Polk'], ['Ford', ' Miss. Doolina Margaret "Daisy"'], ['Richards', ' Mrs. Sidney (Emily Hocking)'], ['Fortune', ' Mr. Mark'], ['Kvillner', ' Mr. Johan Henrik Johannesson'], ['Hart', ' Mrs. Benjamin (Esther Ada Bloomfield)'], ['Hampe', ' Mr. Leon'], ['Petterson', ' Mr. Johan Emil'], ['Reynaldo', ' Ms. Encarnacion'], ['Johannesen-Bratthammer', ' Mr. Bernt'], ['Dodge', ' Master. Washington'], ['Mellinger', ' Miss. Madeleine Violet'], ['Seward', ' Mr. Frederic Kimber'], ['Baclini', ' Miss. Marie Catherine'], ['Peuchen', ' Major. Arthur Godfrey'], ['West', ' Mr. Edwy Arthur'], ['Hagland', ' Mr. Ingvald Olai Olsen'], ['Foreman', ' Mr. Benjamin Laventall'], ['Goldenberg', ' Mr. Samuel L'], ['Peduzzi', ' Mr. Joseph'], ['Jalsevac', ' Mr. Ivan'], ['Millet', ' Mr. Francis Davis'], ['Kenyon', ' Mrs. Frederick R (Marion)'], ['Toomey', ' Miss. Ellen'], ["O'Connor", ' Mr. Maurice'], ['Anderson', ' Mr. Harry'], ['Morley', ' Mr. William'], ['Gee', ' Mr. Arthur H'], ['Milling', ' Mr. Jacob Christian'], ['Maisner', ' Mr. Simon'], ['Goncalves', ' Mr. Manuel Estanslas'], ['Campbell', ' Mr. William'], ['Smart', ' Mr. John Montgomery'], ['Scanlan', ' Mr. James'], ['Baclini', ' Miss. Helene Barbara'], ['Keefe', ' Mr. Arthur'], ['Cacic', ' Mr. Luka'], ['West', ' Mrs. Edwy Arthur (Ada Mary Worth)'], ['Jerwan', ' Mrs. Amin S (Marie Marthe Thuillard)'], ['Strandberg', ' Miss. Ida Sofia'], ['Clifford', ' Mr. George Quincy'], ['Renouf', ' Mr. Peter Henry'], ['Braund', ' Mr. Lewis Richard'], ['Karlsson', ' Mr. Nils August'], ['Hirvonen', ' Miss. Hildur E'], ['Goodwin', ' Master. Harold Victor'], ['Frost', ' Mr. Anthony Wood "Archie"'], ['Rouse', ' Mr. Richard Henry'], ['Turkula', ' Mrs. (Hedwig)'], ['Bishop', ' Mr. Dickinson H'], ['Lefebre', ' Miss. Jeannie'], ['Hoyt', ' Mrs. Frederick Maxfield (Jane Anne Forby)'], ['Kent', ' Mr. Edward Austin'], ['Somerton', ' Mr. Francis William'], ['Coutts', ' Master. Eden Leslie "Neville"'], ['Hagland', ' Mr. Konrad Mathias Reiersen'], ['Windelov', ' Mr. Einar'], ['Molson', ' Mr. Harry Markland'], ['Artagaveytia', ' Mr. Ramon'], ['Stanley', ' Mr. Edward Roland'], ['Yousseff', ' Mr. Gerious'], ['Eustis', ' Miss. Elizabeth Mussey'], ['Shellard', ' Mr. Frederick William'], ['Allison', ' Mrs. Hudson J C (Bessie Waldo Daniels)'], ['Svensson', ' Mr. Olof'], ['Calic', ' Mr. Petar'], ['Canavan', ' Miss. Mary'], ["O'Sullivan", ' Miss. Bridget Mary'], ['Laitinen', ' Miss. Kristina Sofia'], ['Maioni', ' Miss. Roberta'], ['Penasco y Castellana', ' Mr. Victor de Satode'], ['Quick', ' Mrs. Frederick Charles (Jane Richards)'], ['Bradley', ' Mr. George ("George Arthur Brayton")'], ['Olsen', ' Mr. Henry Margido'], ['Lang', ' Mr. Fang'], ['Daly', ' Mr. Eugene Patrick'], ['Webber', ' Mr. James'], ['McGough', ' Mr. James Robert'], ['Rothschild', ' Mrs. Martin (Elizabeth L. Barrett)'], ['Coleff', ' Mr. Satio'], ['Walker', ' Mr. William Anderson'], ['Lemore', ' Mrs. (Amelia Milley)'], ['Ryan', ' Mr. Patrick'], ['Angle', ' Mrs. William A (Florence "Mary" Agnes Hughes)'], ['Pavlovic', ' Mr. Stefo'], ['Perreault', ' Miss. Anne'], ['Vovk', ' Mr. Janko'], ['Lahoud', ' Mr. Sarkis'], ['Hippach', ' Mrs. Louis Albert (Ida Sophia Fischer)'], ['Kassem', ' Mr. Fared'], ['Farrell', ' Mr. James'], ['Ridsdale', ' Miss. Lucy'], ['Farthing', ' Mr. John'], ['Salonen', ' Mr. Johan Werner'], ['Hocking', ' Mr. Richard George'], ['Quick', ' Miss. Phyllis May'], ['Toufik', ' Mr. Nakli'], ['Elias', ' Mr. Joseph Jr'], ['Peter', ' Mrs. Catherine (Catherine Rizk)'], ['Cacic', ' Miss. Marija'], ['Hart', ' Miss. Eva Miriam'], ['Butt', ' Major. Archibald Willingham'], ['LeRoy', ' Miss. Bertha'], ['Risien', ' Mr. Samuel Beard'], ['Frolicher', ' Miss. Hedwig Margaritha'], ['Crosby', ' Miss. Harriet R'], ['Andersson', ' Miss. Ingeborg Constanzia'], ['Andersson', ' Miss. Sigrid Elisabeth'], ['Beane', ' Mr. Edward'], ['Douglas', ' Mr. Walter Donald'], ['Nicholson', ' Mr. Arthur Ernest'], ['Beane', ' Mrs. Edward (Ethel Clarke)'], ['Padro y Manent', ' Mr. Julian'], ['Goldsmith', ' Mr. Frank John'], ['Davies', ' Master. John Morgan Jr'], ['Thayer', ' Mr. John Borland Jr'], ['Sharp', ' Mr. Percival James R'], ["O'Brien", ' Mr. Timothy'], ['Leeni', ' Mr. Fahim ("Philip Zenni")'], ['Ohman', ' Miss. Velin'], ['Wrigh

In [29]:
df1['given_name'] = [i[0] for i in df1['Name'].str.split(',')] ## 이름을 잘라서 콤마 앞에 있는 이름들만 저장
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_simplified,given_name
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,20.0,Braund
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,30.0,Cumings
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,20.0,Heikkinen
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,30.0,Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,30.0,Allen

In [30]:
df1['string_add'] = df1['Sex']+df1['given_name']
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_simplified,given_name,string_add
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,20.0,Braund,maleBraund
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,30.0,Cumings,femaleCumings
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,20.0,Heikkinen,femaleHeikkinen
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,30.0,Futrelle,femaleFutrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,30.0,Allen,maleAllen

In [31]:
df1['number_add'] = df1['Age'] + df1['age_simplified']
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_simplified,given_name,string_add,number_add
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,20.0,Braund,maleBraund,42.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,30.0,Cumings,femaleCumings,68.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,20.0,Heikkinen,femaleHeikkinen,46.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,30.0,Futrelle,femaleFutrelle,65.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,30.0,Allen,maleAllen,65.0

In [32]:
df1.drop('given_name', axis=1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_simplified,string_add,number_add
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,20.0,maleBraund,42.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,30.0,femaleCumings,68.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,20.0,femaleHeikkinen,46.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,30.0,femaleFutrelle,65.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,30.0,maleAllen,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,20.0,maleMontvila,47.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,10.0,femaleGraham,29.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN,femaleJohnston,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,20.0,maleBehr,46.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,30.0,maleDooley,62.0

### **열 이름 변경**
- 열 이름 하나를 바꿀 때
    - `데이터명.rename({열이름:바꿀이름, 열이름:바꿀이름, ...}, axis=1)` ## axis=1 은 고정. 기본적으로 axis가 0으로 설정되어 있기때문에 바꿔줘야 함.
- 열 이름 전체를 바꿀 때
    - `데이터명.columns = 열 이름 리스트`

In [39]:
df1 = df.copy()
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [40]:
df1.rename({'PassengerId':'Id'}, axis=1)

,Id,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df1.columns = [i for i in range(12)]  ## 열이름 변경
df1.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S