# **고급 기능(apply, map, 문자열 다루기)**


---

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import pandas as pd

file_path = r"C:\Users\ryang\OneDrive\문서\공부\part.2\data\titanic_train.csv"
df = pd.read_csv(file_path)

In [ ]:
df.head()

## **apply 함수**  자주 쓰임
- 사용자 정의 함수를 데이터에 적용하고 싶을 때 사용합니다.
- `.apply(함수, axis=0/1)`

In [3]:
df1 = df.copy()

In [4]:
def pclass_sibsp(x):
    if x['Pclass'] == 1 and x['SibSp'] == 1:
        return 1
    else:
        return 0

In [5]:
df1['pclass_sibsp_filter'] = df1.apply(pclass_sibsp, axis=1) ## 열방향으로 계산산

In [6]:
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,pclass_sibsp_filter
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

In [ ]:
import numpy as np

def adult(x):
    if x >= 19:
        return 1
    elif x < 19:
        return 0
    else:
        return np.nan  ## NULL 값 반환환

In [9]:
df1['adult_yn'] = df1['Age'].apply(adult)  # 행방향향
df1.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,pclass_sibsp_filter,adult_yn
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,1.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,1.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,1.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1.0
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,0,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,0,1.0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,0,0.0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,0,1.0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,0,0.0

- 간단한 함수는 lambda로 구현할 수 있습니다.

In [10]:
df1['pclass_sibsp_lambda'] = df1.apply(lambda x: 1 if x['Pclass'] == 1 and x['SibSp'] == 1 else 0, axis=1)
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,pclass_sibsp_filter,adult_yn,pclass_sibsp_lambda
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,1.0,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,1.0,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1.0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,1.0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1.0,0

## **map 함수**
- 값을 특정 값으로 치환하고 싶을 때 사용합니다.
- `데이터명[컬럼명].map(매핑 딕셔너리)`

In [11]:
gender_map = {'male':'남자', 'female':'여자'}
df1['Sex_kr'] = df1['Sex'].map(gender_map)
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,pclass_sibsp_filter,adult_yn,pclass_sibsp_lambda,Sex_kr
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,1.0,0,남자
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,1.0,1,여자
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1.0,0,여자
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,1.0,1,여자
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,1.0,0,남자

## **문자열 다루기**
|메소드|설명|
|:--|:--|
|`.str.contains(문자열)`|문자열을 포함하고 있는지 유무|
|`.str.replace(기존문자열, 대치문자열)`|문자열 대치|
|`.str.split(문자열, expand=True/False, n=개수)`|특정 문자열을 기준으로 쪼개기|
|`.str.lower()`|소문자로 바꾸기|
|`.str.upper()`|대문자로 바꾸기|

In [12]:
df2 = df.copy()
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

- `.str.contains(문자열)`

In [13]:
df2['Name'].str.contains('Mrs')

0      False
1       True
2      False
3       True
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [ ]:
df2[df2['Name'].str.contains('Mrs')] ## 'Mrs' 포함된 행만 추출

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q

- `.str.replace(기존문자열, 대치문자열)`

In [15]:
df2['Name'] = df2['Name'].str.replace(',', '')
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Braund Mr. Owen Harris,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,Cumings Mrs. John Bradley (Florence Briggs Tha...,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,Heikkinen Miss. Laina,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,Futrelle Mrs. Jacques Heath (Lily May Peel),female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,Allen Mr. William Henry,male,35.0,0,0,373450,8.0500,NaN,S

- `.str.split(문자열, expand=True/False, n=개수)`

In [16]:
df2['Name'].str.split(' ')

0                            [Braund, Mr., Owen, Harris]
1      [Cumings, Mrs., John, Bradley, (Florence, Brig...
2                              [Heikkinen, Miss., Laina]
3      [Futrelle, Mrs., Jacques, Heath, (Lily, May, P...
4                           [Allen, Mr., William, Henry]
                             ...
886                             [Montvila, Rev., Juozas]
887                     [Graham, Miss., Margaret, Edith]
888        [Johnston, Miss., Catherine, Helen, "Carrie"]
889                            [Behr, Mr., Karl, Howell]
890                               [Dooley, Mr., Patrick]
Name: Name, Length: 891, dtype: object

In [17]:
df2['Name'].str.split(' ', expand=True, n=1)

             0                                           1
0       Braund                             Mr. Owen Harris
1      Cumings  Mrs. John Bradley (Florence Briggs Thayer)
2    Heikkinen                                 Miss. Laina
3     Futrelle          Mrs. Jacques Heath (Lily May Peel)
4        Allen                           Mr. William Henry
..         ...                                         ...
886   Montvila                                 Rev. Juozas
887     Graham                        Miss. Margaret Edith
888   Johnston              Miss. Catherine Helen "Carrie"
889       Behr                             Mr. Karl Howell
890     Dooley                                 Mr. Patrick

[891 rows x 2 columns]

- `.str.lower()`
- `.str.upper()`

In [18]:
df2['Name'].str.lower()

0                                 braund mr. owen harris
1      cumings mrs. john bradley (florence briggs tha...
2                                  heikkinen miss. laina
3            futrelle mrs. jacques heath (lily may peel)
4                                allen mr. william henry
                             ...
886                                 montvila rev. juozas
887                          graham miss. margaret edith
888              johnston miss. catherine helen "carrie"
889                                 behr mr. karl howell
890                                   dooley mr. patrick
Name: Name, Length: 891, dtype: object

In [19]:
df2['Name'].str.upper()

0                                 BRAUND MR. OWEN HARRIS
1      CUMINGS MRS. JOHN BRADLEY (FLORENCE BRIGGS THA...
2                                  HEIKKINEN MISS. LAINA
3            FUTRELLE MRS. JACQUES HEATH (LILY MAY PEEL)
4                                ALLEN MR. WILLIAM HENRY
                             ...
886                                 MONTVILA REV. JUOZAS
887                          GRAHAM MISS. MARGARET EDITH
888              JOHNSTON MISS. CATHERINE HELEN "CARRIE"
889                                 BEHR MR. KARL HOWELL
890                                   DOOLEY MR. PATRICK
Name: Name, Length: 891, dtype: object