# **stack, unstack, melt**


---

## **stack, unstack**
 - stack : 컬럼 레벨에서 인덱스 레벨로 데이터프레임을 변경합니다.
 - unstack : 인덱스 레벨에서 컬럼 레벨로 데이터프레임을 변경합니다.
  - stack의 반대입니다.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import pandas as pd

file_path = r'./data/titanic_train.csv'
df = pd.read_csv(file_path)

In [2]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
pivot = pd.pivot_table(df, index=['Sex','Pclass'], values=['Survived','Fare'], aggfunc=['mean','median','sum'])
pivot

                     mean              median                 sum
                     Fare  Survived      Fare Survived       Fare Survived
Sex    Pclass
female 1       106.125798  0.968085  82.66455      1.0  9975.8250       91
       2        21.970121  0.921053  22.00000      1.0  1669.7292       70
       3        16.118810  0.500000  12.47500      0.5  2321.1086       72
male   1        67.226127  0.368852  41.26250      0.0  8201.5875       45
       2        19.741782  0.157407  13.00000      0.0  2132.1125       17
       3        12.661633  0.135447   7.92500      0.0  4393.5865       47

In [ ]:
pivot.stack(0) #컬럼의 첫번째(0) 레벨을 인덱스로 내립니다. (mean, median, sum 이 인덱스로 내려갔다.)

C:\Users\1\AppData\Local\Temp\ipykernel_2972\931120016.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  pivot.stack(0) #컬럼의 첫번째 레벨을 인덱스로 내립니다.

                             Fare   Survived
Sex    Pclass
female 1      mean     106.125798   0.968085
              median    82.664550   1.000000
              sum     9975.825000  91.000000
       2      mean      21.970121   0.921053
              median    22.000000   1.000000
              sum     1669.729200  70.000000
       3      mean      16.118810   0.500000
              median    12.475000   0.500000
              sum     2321.108600  72.000000
male   1      mean      67.226127   0.368852
              median    41.262500   0.000000
              sum     8201.587500  45.000000
       2      mean      19.741782   0.157407
              median    13.000000   0.000000
              sum     2132.112500  17.000000
       3      mean      12.661633   0.135447
              median     7.925000   0.000000
              sum     4393.586500  47.000000

In [ ]:
pivot.stack(1) #컬럼의 두번째 레벨을 인덱스로 내립니다. fare, Survived가 인덱스로 내려갔다.

C:\Users\1\AppData\Local\Temp\ipykernel_2972\3127299118.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  pivot.stack(1) #컬럼의 두번째 레벨을 인덱스로 내립니다.

                              mean    median        sum
Sex    Pclass
female 1      Fare      106.125798  82.66455  9975.8250
              Survived    0.968085   1.00000    91.0000
       2      Fare       21.970121  22.00000  1669.7292
              Survived    0.921053   1.00000    70.0000
       3      Fare       16.118810  12.47500  2321.1086
              Survived    0.500000   0.50000    72.0000
male   1      Fare       67.226127  41.26250  8201.5875
              Survived    0.368852   0.00000    45.0000
       2      Fare       19.741782  13.00000  2132.1125
              Survived    0.157407   0.00000    17.0000
       3      Fare       12.661633   7.92500  4393.5865
              Survived    0.135447   0.00000    47.0000

In [ ]:
pivot.unstack(0) #인덱스의 첫번째 레벨을 컬럼으로 쌓아 올립니다. 첫번째 인덱스의 Sex가 컬럼으로 올라갔다

              mean                                   median                    \
              Fare             Survived                Fare          Survived
Sex         female       male    female      male    female     male   female
Pclass
1       106.125798  67.226127  0.968085  0.368852  82.66455  41.2625      1.0
2        21.970121  19.741782  0.921053  0.157407  22.00000  13.0000      1.0
3        16.118810  12.661633  0.500000  0.135447  12.47500   7.9250      0.5

                   sum
                  Fare            Survived
Sex    male     female       male   female male
Pclass
1       0.0  9975.8250  8201.5875       91   45
2       0.0  1669.7292  2132.1125       70   17
3       0.0  2321.1086  4393.5865       72   47

In [ ]:
pivot.unstack(1) #인덱스의 두번째 레벨을 컬럼으로 쌓아 올립니다. 두번째 레벨이었던 pclass가 컬럼으로 올라갔다.

              mean                                                      \
              Fare                        Survived
Pclass           1          2          3         1         2         3
Sex
female  106.125798  21.970121  16.118810  0.968085  0.921053  0.500000
male     67.226127  19.741782  12.661633  0.368852  0.157407  0.135447

          median                                         sum             \
            Fare               Survived                 Fare
Pclass         1     2       3        1    2    3          1          2
Sex
female  82.66455  22.0  12.475      1.0  1.0  0.5  9975.8250  1669.7292
male    41.26250  13.0   7.925      0.0  0.0  0.0  8201.5875  2132.1125


                  Survived
Pclass          3        1   2   3
Sex
female  2321.1086       91  70  72
male    4393.5865       45  17  47

## **melt**
- wide 데이터를 long 데이터로 바꾸는 함수
- `pd.melt(데이터명, id_vars=기준 컬럼)` 그림에서는 name
![이미지](https://i0.wp.com/cmdlinetips.com/wp-content/uploads/2019/06/Pandas_melt_reshape.png?w=421&ssl=1)

In [8]:
data = pd.DataFrame({'name':['a','b','c']
                    , 'order_count':[3,4,10]
                    , 'amount':[10000,25000,300000]})

In [9]:
data

  name  order_count  amount
0    a            3   10000
1    b            4   25000
2    c           10  300000

In [ ]:
pd.melt(data, id_vars=['name']) ## id_vars : 고정할 열

  name     variable   value
0    a  order_count       3
1    b  order_count       4
2    c  order_count      10
3    a       amount   10000
4    b       amount   25000
5    c       amount  300000

In [ ]:
pd.melt(data, id_vars=['name'], var_name='type', value_name='val')  ## 이름 바꾸기

  name         type     val
0    a  order_count       3
1    b  order_count       4
2    c  order_count      10
3    a       amount   10000
4    b       amount   25000
5    c       amount  300000