# **피벗테이블**
- 엑셀의 피벗테이블처럼 인덱스별 컬럼별 값의 연산을 할 수 있습니다.  
crosstab은 범주용 데이터를 이용해서 각 범주별로 행의 개수를 구했다. 
but 피벗테이블은 값에 연산 가능
- `pd.pivot_table(데이터명, index=, columns=, values=, aggfunc=)`

---

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import pandas as pd

file_path = r'./data/titanic_train.csv'
df = pd.read_csv(file_path)

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## **단일 인덱스, 단일 컬럼, 단일 값**

In [6]:
pd.pivot_table(df, index='Sex', columns='Pclass', values='Survived', aggfunc='mean')
## 성별이 인덱스, Pclass가 컬럼, Survived의 값으로 평균을 구함

Pclass         1         2         3
Sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
pd.pivot_table(df, index='Pclass', columns='Sex', values='Survived', aggfunc='mean')
## 인덱스, 컬럼 반대로

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

In [8]:
pd.pivot_table(df, index='Sex', columns='SibSp', values='Survived', aggfunc='mean')

SibSp          0         1         2         3         4    5    8
Sex
female  0.787356  0.754717  0.769231  0.363636  0.333333  0.0  0.0
male    0.168203  0.310680  0.200000  0.000000  0.083333  0.0  0.0

In [9]:
pd.pivot_table(df, index='Sex', columns='Survived', values='Age', aggfunc='mean')

Survived          0          1
Sex
female    25.046875  28.847716
male      31.618056  27.276022

- `margins` 옵션을 통해 행과 열 전체의 값도 구할 수 있습니다.

In [ ]:
pd.pivot_table(df, index='Sex', columns='Survived', values='Age', aggfunc='mean', margins=True)
## margins=True : 행과 열 전체 평균값 구하기 가능

Survived          0          1        All
Sex
female    25.046875  28.847716  27.915709
male      31.618056  27.276022  30.726645
All       30.626179  28.343690  29.699118

In [ ]:
pd.pivot_table(df, index='Sex', columns='Survived', values='Age', aggfunc=['max','min','mean'])
## aggfunc에 여러 개의 함수를 넣을 수 있음

           max        min             mean
Survived     0     1    0     1          0          1
Sex
female    57.0  63.0  2.0  0.75  25.046875  28.847716
male      74.0  80.0  1.0  0.42  31.618056  27.276022

## **다중 인덱스, 다중 컬럼, 다중 값**

In [ ]:
pd.pivot_table(df, index=['Sex','Pclass'], columns='Survived', values='Age', aggfunc='mean')
## 다중 인덱스 사용 가능(리스트 사용)

Survived               0          1
Sex    Pclass
female 1       25.666667  34.939024
       2       36.000000  28.080882
       3       23.818182  19.329787
male   1       44.581967  36.248000
       2       33.369048  16.022000
       3       27.255814  22.274211

In [ ]:
pd.pivot_table(df, index='Survived', columns=['Sex','Pclass'], values='Age', aggfunc='mean')
## 다중 컬럼 사용 가능(리스트 사용)

In [ ]:
pd.pivot_table(df, index=['Sex','Pclass'], columns=['Survived','Embarked'], values='Age', aggfunc='mean')
## 다중 인덱스, 다중 컬럼 사용 가능(리스트 사용)

Survived               0                                1
Embarked               C          Q          S          C     Q          S
Sex    Pclass
female 1       50.000000        NaN  13.500000  35.675676  33.0  33.619048
       2             NaN        NaN  36.000000  19.142857  30.0  29.091667
       3       20.700000  28.100000  23.688889  11.045455  17.6  22.548387
male   1       43.050000  44.000000  45.362500  36.437500   NaN  36.121667
       2       29.500000  57.000000  33.414474   1.000000   NaN  17.095000
       3       27.555556  28.076923  27.168478  18.488571  29.0  22.933333

In [ ]:
pd.pivot_table(df, index=['Sex','Pclass'], columns=['Survived','Embarked'], values=['Age','Fare'], aggfunc='mean')
## 다중 인덱스, 다중 컬럼, 다중 값 사용 가능(리스트 사용)

                     Age                                                    \
Survived               0                                1
Embarked               C          Q          S          C     Q          S
Sex    Pclass
female 1       50.000000        NaN  13.500000  35.675676  33.0  33.619048
       2             NaN        NaN  36.000000  19.142857  30.0  29.091667
       3       20.700000  28.100000  23.688889  11.045455  17.6  22.548387
male   1       43.050000  44.000000  45.362500  36.437500   NaN  36.121667
       2       29.500000  57.000000  33.414474   1.000000   NaN  17.095000
       3       27.555556  28.076923  27.168478  18.488571  29.0  22.933333

                    Fare                                                \
Survived               0                                  1
Embarked               C          Q           S           C          Q
Sex    Pclass
female 1       28.712500        NaN  151.550000  117.710019  90.000000
       2             NaN        NaN   18.250000   25.268457  12.350000
       3       14.653125  10.904633   21.969018   14.717220  10.084033
male   1       80.847160  90.000000   53.563316  112.197806        NaN
       2       25.418225  12.350000   18.997561   25.433350        NaN
       3        8.720842  11.841550   12.758689   11.435840  12.916667


Survived
Embarked               S
Sex    Pclass
female 1       96.743298
       2       22.272951
       3       13.171842
male   1       51.832739
       2       20.516667
       3       17.033450