# **부동산 데이터: 최적의 자취방 구하기**

## **크롤링**

In [5]:
pip install user-agent

Requirement already satisfied: user-agent in c:\users\ryang\appdata\local\programs\python\python313\lib\site-packages (0.1.10)
Requirement already satisfied: six in c:\users\ryang\appdata\roaming\python\python313\site-packages (from user-agent) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
from user_agent import generate_user_agent, generate_navigator
user_agent = generate_user_agent()
user_agent

'Mozilla/5.0 (Windows NT 6.2; Trident/7.0; rv:11.0) like Gecko'

In [6]:
import requests
import numpy as np
import pandas as pd

In [7]:
from tqdm.notebook import tqdm
import time

In [11]:
article_list = []
for i in tqdm(range(1, 101)):
    try:
        url = f'https://m.land.naver.com/cluster/ajax/articleList?itemId=&mapKey=&lgeo=&showR0=&rletTpCd=OPST%3AVL%3AOR&tradTpCd=B2&z=12&lat=37.481021&lon=126.951601&btm=37.3398975&lft=126.6762562&top=37.6218785&rgt=127.2269458&totCnt=8360&cortarNo=1162000000&sort=rank&page={i}'

        user_agent = generate_user_agent()
        headers = {'User-Agent':user_agent}

        res = requests.get(url, headers=headers)
        time.sleep(1)

        article_json = res.json()
        article_body = article_json['body']
        article_list.append(article_body)
    except:
        break

  0%|          | 0/100 [00:00<?, ?it/s]

In [64]:
article_list1 = [j for i in article_list for j in i]

In [66]:
data = pd.DataFrame(article_list1)

In [68]:
data = data[['atclNo','rletTpNm','flrInfo','rentPrc','hanPrc','spc1','spc2','direction','atclCfmYmd','repImgUrl','lat','lng','atclFetrDesc','tagList']]
data.columns = ['물건번호','구분','층수(물건층/전체층)','월세','보증금','계약면적(m2)','전용면적(m2)','방향','확인일자','이미지','위도','경도','설명','태그']
data

,물건번호,구분,층수(물건층/전체층),월세,보증금,계약면적(m2),전용면적(m2),방향,확인일자,이미지,위도,경도,설명,태그
0,2339667467,원룸,2/4,55,"1,000",26,19.8,남서향,23.09.15.,/20230915_104/land_naver_1694770741540Yco5Q_JP...,37.479689,126.939191,봉천역도보권 신축급 채광좋고 방사이즈 좋은 깔끔한 분리형원룸,"[10년이내, 융자금적은, 역세권]"
1,2339651668,원룸,중/7,40,"1,000",19,16.5,북동향,23.09.15.,/20230915_166/land_naver_16947709207628XSkm_JP...,37.479887,126.946841,"SUV 무료주차 좋음 , 보안 CCTV 좋음 정남향","[25년이내, 융자금없는, 소형평수]"
2,2339487647,원룸,4/8,43,100,19,19.9,북향,23.09.15.,/20230915_251/land_naver_1694787000581r4F16_JP...,37.485412,126.932721,애완동물가능 신림역원룸 저렴하기로 최고 가성비갑원룸,"[25년이내, 융자금적은, 역세권]"
3,2339568890,원룸,2/5,40,"1,000",20,16,서향,23.09.15.,/20230915_271/land_naver_1694770562663jy052_JP...,37.478551,126.964993,낙성대역세권 수리되어 깔끔한 원룸,"[25년이내, 융자금적은, 역세권]"
4,2339676856,원룸,7/9,33,200,19,16.52,남향,23.09.15.,/20230915_180/land_naver_1694787002217YGslS_JP...,37.485598,126.928802,신림역 도보 2분 가성비 좋은 지상층 원룸,"[15년이내, 융자금없는, 역세권]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2339187707,원룸,3/4,35,300,23,19.84,남동향,23.09.12.,/20230912_116/land_naver_1694487156013f9nE6_JP...,37.478363,126.962085,고시원보다 싼 주차가능한 풀옵션 꿀매물 미쳤다,"[25년이상, 융자금적은, 역세권]"
1996,2339171817,원룸,3/6,10,"1억 5,000",29,26.44,남향,23.09.12.,/20230912_90/land_naver_1694485518591OfHlz_JPE...,37.484940,126.947014,봉천역서울대입구역 1.5룸 신축급 전세 놓치지마세요,"[10년이내, 융자금적은, 소형평수]"
1997,2339196833,원룸,1/3,60,"1,000",-,29,북동향,23.09.12.,/20230912_88/land_naver_1694488675773UOkqf_JPE...,37.476486,126.932206,가성비넘나 좋은 그방,"[10년이내, 융자금적은, 역세권]"
1998,2339193479,원룸,1/5,65,"5,000",-,24,남동향,23.09.12.,/20230912_295/land_naver_1694488276372z8vWM_JP...,37.482470,126.924457,"신축급, 위치좋은 깔끔한집","[2년이내, 융자금적은, 1층]"
1999,2339173014,원룸,1/5,30,"1,000",-,16.52,남동향,23.09.12.,/20230912_230/land_naver_1694484914347J0J85_JP...,37.479498,126.932206,2호선 역세권 지상층 가성비 깔끔한 원룸 보증금 조정 가능,"[25년이내, 융자금적은, 역세권]"

In [69]:
data.to_excel('/content/drive/MyDrive/강의자료_황수현_Python/Part3) 파이썬 데이터 분석 프로젝트/data/실습6: 직접 크롤링하기 - 부동산 데이터 분석을 통해 최적의 자취방 구하기/data.xlsx')

## **질문 만들기**

- 최적의 자취방 구하기
    - 내가 원하는 조건은?
        1. 보증금 3000만원 이하
        2. 월세는 저렴할수록 좋음
        3. 지하, 반지하, 꼭대기층은 선호하지 않음
        4. 전용면적이 클수록 좋음
        5. 북향은 선호하지 않음
        6. 연식이 오래되지 않을수록 좋음
        7. 지하철 역에서 가까울수록 좋음

## **데이터 전처리**

In [2]:
import plotly.express as px
import folium

import warnings
warnings.filterwarnings(action='ignore')

In [9]:
data = pd.read_excel(r"C:\Users\ryang\OneDrive\문서\공부\ryang_python_practice\part.3\Data\실습6_ 직접 크롤링하기 - 부동산 데이터 분석을 통해 최적의 자취방 구하기\data.xlsx")

In [10]:
data.head()

,Unnamed: 0,물건번호,구분,층수(물건층/전체층),월세,보증금,계약면적(m2),전용면적(m2),방향,확인일자,이미지,위도,경도,설명,태그
0,0,2339667467,원룸,2/4,55,"1,000",26,19.80,남서향,23.09.15.,/20230915_104/land_naver_1694770741540Yco5Q_JP...,37.479689,126.939191,봉천역도보권 신축급 채광좋고 방사이즈 좋은 깔끔한 분리형원룸,"['10년이내', '융자금적은', '역세권']"
1,1,2339651668,원룸,중/7,40,"1,000",19,16.50,북동향,23.09.15.,/20230915_166/land_naver_16947709207628XSkm_JP...,37.479887,126.946841,"SUV 무료주차 좋음 , 보안 CCTV 좋음 정남향","['25년이내', '융자금없는', '소형평수']"
2,2,2339487647,원룸,4/8,43,100,19,19.90,북향,23.09.15.,/20230915_251/land_naver_1694787000581r4F16_JP...,37.485412,126.932721,애완동물가능 신림역원룸 저렴하기로 최고 가성비갑원룸,"['25년이내', '융자금적은', '역세권']"
3,3,2339568890,원룸,2/5,40,"1,000",20,16.00,서향,23.09.15.,/20230915_271/land_naver_1694770562663jy052_JP...,37.478551,126.964993,낙성대역세권 수리되어 깔끔한 원룸,"['25년이내', '융자금적은', '역세권']"
4,4,2339676856,원룸,7/9,33,200,19,16.52,남향,23.09.15.,/20230915_180/land_naver_1694787002217YGslS_JP...,37.485598,126.928802,신림역 도보 2분 가성비 좋은 지상층 원룸,"['15년이내', '융자금없는', '역세권']"

In [11]:
data = data.iloc[:,1:]

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   물건번호         2000 non-null   int64
 1   구분           2000 non-null   object
 2   층수(물건층/전체층)  2000 non-null   object
 3   월세           2000 non-null   int64
 4   보증금          2000 non-null   object
 5   계약면적(m2)     2000 non-null   object
 6   전용면적(m2)     2000 non-null   float64
 7   방향           2000 non-null   object
 8   확인일자         2000 non-null   object
 9   이미지          1912 non-null   object
 10  위도           2000 non-null   float64
 11  경도           2000 non-null   float64
 12  설명           1841 non-null   object
 13  태그           2000 non-null   object
dtypes: float64(3), int64(2), object(9)
memory usage: 218.9+ KB

- 월세 0원인 경우 제외

In [13]:
data = data.query('월세 > 0')

- 보증금 숫자로 변환

In [14]:
data['보증금'].unique()

array(['1,000', '100', '200', '1억', '300', '500', '4,000', '3,000',
       '5,000', '2,000', '3,700', '6,000', '3억', '1억 3,500', '2,500',
       '150', '50', '9,000', '8,500', '2억 2,000', '1억 2,000', '2억', '70',
       '7,000', '1억 1,000', '8,000', '6,500', '1억 6,000', '1억 4,000',
       '1억 5,000', '700', '5,500', '7,600', '60', '3억 2,000', '600',
       '1억 9,000', '2억 7,650', '1억 8,000', '8,900', '7,500', '2억 4,000',
       '2억 9,800', '2억 7,300', '1억 3,000', '1억 2,500', '2억 5,000',
       '2억 3,000', '2억 6,000', '2억 8,900', '3,500', '8,700', '2억 9,000',
       '2억 4,600', '2억 8,500', '1억 7,000', '400', '2억 3,560', '1,500',
       '6,450', '1,100', '1억 7,500', '1억 9,800', '3,400'], dtype=object)

In [15]:
data = data.query('~보증금.str.contains("억")')

In [16]:
data['보증금'].unique()

array(['1,000', '100', '200', '300', '500', '4,000', '3,000', '5,000',
       '2,000', '3,700', '6,000', '2,500', '150', '50', '9,000', '8,500',
       '70', '7,000', '8,000', '6,500', '700', '5,500', '7,600', '60',
       '600', '8,900', '7,500', '3,500', '8,700', '400', '1,500', '6,450',
       '1,100', '3,400'], dtype=object)

In [17]:
data['보증금'] = data['보증금'].str.replace(',','').astype(int)
data['보증금'].unique()

array([1000,  100,  200,  300,  500, 4000, 3000, 5000, 2000, 3700, 6000,
       2500,  150,   50, 9000, 8500,   70, 7000, 8000, 6500,  700, 5500,
       7600,   60,  600, 8900, 7500, 3500, 8700,  400, 1500, 6450, 1100,
       3400])

- 물건층과 전체층 분리 후 1층과 꼭대기층 유무 컬럼 만들기
    - 지하의 경우 마이너스로 표시

In [18]:
data[['물건층','전체층']] = data['층수(물건층/전체층)'].str.split('/', expand=True)

In [19]:
data.head()

,물건번호,구분,층수(물건층/전체층),월세,보증금,계약면적(m2),전용면적(m2),방향,확인일자,이미지,위도,경도,설명,태그,물건층,전체층
0,2339667467,원룸,2/4,55,1000,26,19.80,남서향,23.09.15.,/20230915_104/land_naver_1694770741540Yco5Q_JP...,37.479689,126.939191,봉천역도보권 신축급 채광좋고 방사이즈 좋은 깔끔한 분리형원룸,"['10년이내', '융자금적은', '역세권']",2,4
1,2339651668,원룸,중/7,40,1000,19,16.50,북동향,23.09.15.,/20230915_166/land_naver_16947709207628XSkm_JP...,37.479887,126.946841,"SUV 무료주차 좋음 , 보안 CCTV 좋음 정남향","['25년이내', '융자금없는', '소형평수']",중,7
2,2339487647,원룸,4/8,43,100,19,19.90,북향,23.09.15.,/20230915_251/land_naver_1694787000581r4F16_JP...,37.485412,126.932721,애완동물가능 신림역원룸 저렴하기로 최고 가성비갑원룸,"['25년이내', '융자금적은', '역세권']",4,8
3,2339568890,원룸,2/5,40,1000,20,16.00,서향,23.09.15.,/20230915_271/land_naver_1694770562663jy052_JP...,37.478551,126.964993,낙성대역세권 수리되어 깔끔한 원룸,"['25년이내', '융자금적은', '역세권']",2,5
4,2339676856,원룸,7/9,33,200,19,16.52,남향,23.09.15.,/20230915_180/land_naver_1694787002217YGslS_JP...,37.485598,126.928802,신림역 도보 2분 가성비 좋은 지상층 원룸,"['15년이내', '융자금없는', '역세권']",7,9

In [20]:
data['물건층'].unique()

array(['2', '중', '4', '7', '저', '3', '1', '5', 'B1', '13', '8', '6', '고',
       '11', '9', '10', '17', '12', '22', 'B2'], dtype=object)

In [21]:
def floor_info(target, total):
    try:
        if target in ['B1','B2']: #지하이면
            return 'y'
        elif int(target) == 1 or int(target)/int(total) == 1: #1층이거나 꼭대기층이면
            return 'y'
        else:
            return 'n'
    except ValueError:
        return 'n'

In [22]:
data['비선호층여부'] = data.apply(lambda x: floor_info(x['물건층'], x['전체층']), axis=1)

In [23]:
data.head()

,물건번호,구분,층수(물건층/전체층),월세,보증금,계약면적(m2),전용면적(m2),방향,확인일자,이미지,위도,경도,설명,태그,물건층,전체층,비선호층여부
0,2339667467,원룸,2/4,55,1000,26,19.80,남서향,23.09.15.,/20230915_104/land_naver_1694770741540Yco5Q_JP...,37.479689,126.939191,봉천역도보권 신축급 채광좋고 방사이즈 좋은 깔끔한 분리형원룸,"['10년이내', '융자금적은', '역세권']",2,4,n
1,2339651668,원룸,중/7,40,1000,19,16.50,북동향,23.09.15.,/20230915_166/land_naver_16947709207628XSkm_JP...,37.479887,126.946841,"SUV 무료주차 좋음 , 보안 CCTV 좋음 정남향","['25년이내', '융자금없는', '소형평수']",중,7,n
2,2339487647,원룸,4/8,43,100,19,19.90,북향,23.09.15.,/20230915_251/land_naver_1694787000581r4F16_JP...,37.485412,126.932721,애완동물가능 신림역원룸 저렴하기로 최고 가성비갑원룸,"['25년이내', '융자금적은', '역세권']",4,8,n
3,2339568890,원룸,2/5,40,1000,20,16.00,서향,23.09.15.,/20230915_271/land_naver_1694770562663jy052_JP...,37.478551,126.964993,낙성대역세권 수리되어 깔끔한 원룸,"['25년이내', '융자금적은', '역세권']",2,5,n
4,2339676856,원룸,7/9,33,200,19,16.52,남향,23.09.15.,/20230915_180/land_naver_1694787002217YGslS_JP...,37.485598,126.928802,신림역 도보 2분 가성비 좋은 지상층 원룸,"['15년이내', '융자금없는', '역세권']",7,9,n

- 제외 조건에 해당하는 매물 제외
    - 내가 원하는 조건은?
        1. 보증금 3000만원 이하
        2. 월세는 저렴할수록 좋음
        3. 지하, 반지하, 꼭대기층은 선호하지 않음
        4. 전용면적이 클수록 좋음
        5. 북향은 선호하지 않음
        6. 연식이 오래되지 않을수록 좋음
        7. 지하철 역에서 가까울수록 좋음

In [24]:
#보증금 3000만원 이하
#지하, 반지하, 꼭대기층은 선호하지 않음
#북향은 선호하지 않음
data_filtered = data.query('300 <= 보증금 <= 3000 and 비선호층여부 == "n" and 전체층 != "1" and ~방향.str.contains("북")')

In [25]:
data_filtered

,물건번호,구분,층수(물건층/전체층),월세,보증금,계약면적(m2),전용면적(m2),방향,확인일자,이미지,위도,경도,설명,태그,물건층,전체층,비선호층여부
0,2339667467,원룸,2/4,55,1000,26,19.80,남서향,23.09.15.,/20230915_104/land_naver_1694770741540Yco5Q_JP...,37.479689,126.939191,봉천역도보권 신축급 채광좋고 방사이즈 좋은 깔끔한 분리형원룸,"['10년이내', '융자금적은', '역세권']",2,4,n
3,2339568890,원룸,2/5,40,1000,20,16.00,서향,23.09.15.,/20230915_271/land_naver_1694770562663jy052_JP...,37.478551,126.964993,낙성대역세권 수리되어 깔끔한 원룸,"['25년이내', '융자금적은', '역세권']",2,5,n
8,2339681933,원룸,3/6,45,300,19,16.52,서향,23.09.15.,/20230915_295/land_naver_1694786940564F4hWf_JP...,37.486020,126.927202,신림역 가성비 짱 분리형 원룸 위치도 너무 좋아요,"['15년이내', '융자금없는', '역세권']",3,6,n
10,2339663561,원룸,저/4,35,500,26,19.80,서향,23.09.15.,/20230915_24/land_naver_1694770860861HB3gt_JPE...,37.484998,126.952802,서울대입구역도보권 신축급 가성비좋은 깨끗한 풀옵션원룸,"['10년이내', '융자금적은', '역세권']",저,4,n
14,2339661926,원룸,저/4,50,1000,26,19.80,동향,23.09.15.,/20230915_72/land_naver_1694770860633nCaXR_JPE...,37.484270,126.949405,서울대입구역도보권 방크기 좋은 깔끔한 분리형원룸,"['15년이내', '융자금적은', '세대분리']",저,4,n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,2339185628,빌라,중/4,100,2000,42,39.67,남동향,23.09.12.,/20230912_39/land_naver_1694487076985hxWAX_JPE...,37.473537,126.963900,NaN,"['15년이내', '융자금적은', '역세권']",중,4,n
1986,2339175088,원룸,저/3,40,500,23,21.00,남동향,23.09.12.,/20230912_15/land_naver_1694486124687snJyq_JPE...,37.474253,126.977329,역세권 깔끔하고 좋은 집 나왔습니다,"['15년이내', '융자금없는', '화장실한개']",저,3,n
1988,2339199717,원룸,고/4,45,500,26,21.49,남동향,23.09.12.,/20230914_12/land_naver_1694688064189IVgCU_JPE...,37.475558,126.936207,도림천뷰 인스타감성 초역세권 원룸꾸미기,"['25년이상', '융자금적은', '역세권']",고,4,n
1989,2339203612,빌라,3/5,90,2000,52,45.60,서향,23.09.12.,NaN,37.472359,126.919879,대로변 버스정류장바로 뒤.올수리.거실있는 방3개 빌라,"['25년이내', '융자금없는', '올수리', '화장실한개']",3,5,n
1995,2339187707,원룸,3/4,35,300,23,19.84,남동향,23.09.12.,/20230912_116/land_naver_1694487156013f9nE6_JP...,37.478363,126.962085,고시원보다 싼 주차가능한 풀옵션 꿀매물 미쳤다,"['25년이상', '융자금적은', '역세권']",3,4,n

- 태그 컬럼 분리

In [26]:
data_filtered[['tag1','tag2','tag3','tag4']] = data_filtered['태그'].str.replace("\'|\[|\]","").str.split(', ', expand=True)

In [27]:
data_filtered.head()

,물건번호,구분,층수(물건층/전체층),월세,보증금,계약면적(m2),전용면적(m2),방향,확인일자,이미지,...,경도,설명,태그,물건층,전체층,비선호층여부,tag1,tag2,tag3,tag4
0,2339667467,원룸,2/4,55,1000,26,19.80,남서향,23.09.15.,/20230915_104/land_naver_1694770741540Yco5Q_JP...,...,126.939191,봉천역도보권 신축급 채광좋고 방사이즈 좋은 깔끔한 분리형원룸,"['10년이내', '융자금적은', '역세권']",2,4,n,['10년이내','융자금적은','역세권'],None
3,2339568890,원룸,2/5,40,1000,20,16.00,서향,23.09.15.,/20230915_271/land_naver_1694770562663jy052_JP...,...,126.964993,낙성대역세권 수리되어 깔끔한 원룸,"['25년이내', '융자금적은', '역세권']",2,5,n,['25년이내','융자금적은','역세권'],None
8,2339681933,원룸,3/6,45,300,19,16.52,서향,23.09.15.,/20230915_295/land_naver_1694786940564F4hWf_JP...,...,126.927202,신림역 가성비 짱 분리형 원룸 위치도 너무 좋아요,"['15년이내', '융자금없는', '역세권']",3,6,n,['15년이내','융자금없는','역세권'],None
10,2339663561,원룸,저/4,35,500,26,19.80,서향,23.09.15.,/20230915_24/land_naver_1694770860861HB3gt_JPE...,...,126.952802,서울대입구역도보권 신축급 가성비좋은 깨끗한 풀옵션원룸,"['10년이내', '융자금적은', '역세권']",저,4,n,['10년이내','융자금적은','역세권'],None
14,2339661926,원룸,저/4,50,1000,26,19.80,동향,23.09.15.,/20230915_72/land_naver_1694770860633nCaXR_JPE...,...,126.949405,서울대입구역도보권 방크기 좋은 깔끔한 분리형원룸,"['15년이내', '융자금적은', '세대분리']",저,4,n,['15년이내','융자금적은','세대분리'],None

- 연식 컬럼 추가

In [28]:
data_filtered = data_filtered.query('tag1.str.contains("년")') #연식 정보가 있는 데이터만 필터링

In [29]:
data_filtered['연식'] = [int(i[0]) for i in data_filtered['tag1'].str.split('년')]
data_filtered

ValueError: invalid literal for int() with base 10: "['10"

In [30]:
def extract_year(value):
    try:
        # '년'이 있는 경우에만 처리
        if '년' in value:
            # '년'을 기준으로 분리하고 첫 번째 값을 가져온 뒤, 공백 제거하고 숫자로 변환
            year_str = value.split('년')[0].strip()
            return int(year_str)
        return None
    except:
        return None

# 함수 적용
data_filtered['연식'] = data_filtered['tag1'].apply(extract_year)

- 필요한 컬럼만 남기기

In [31]:
data_filtered.columns

Index(['물건번호', '구분', '층수(물건층/전체층)', '월세', '보증금', '계약면적(m2)', '전용면적(m2)', '방향',
       '확인일자', '이미지', '위도', '경도', '설명', '태그', '물건층', '전체층', '비선호층여부', 'tag1',
       'tag2', 'tag3', 'tag4', '연식'],
      dtype='object')

In [32]:
data_filtered = data_filtered[['물건번호','월세','보증금','전용면적(m2)','방향','위도','경도','물건층','전체층','연식']]
data_filtered.head()

          물건번호  월세   보증금  전용면적(m2)   방향         위도          경도 물건층 전체층    연식
0   2339667467  55  1000     19.80  남서향  37.479689  126.939191   2   4  None
3   2339568890  40  1000     16.00   서향  37.478551  126.964993   2   5  None
8   2339681933  45   300     16.52   서향  37.486020  126.927202   3   6  None
10  2339663561  35   500     19.80   서향  37.484998  126.952802   저   4  None
14  2339661926  50  1000     19.80   동향  37.484270  126.949405   저   4  None

- 위도, 경도를 이용하여 역까지의 거리 재기

In [33]:
coordinate = pd.read_csv(r"C:\Users\ryang\OneDrive\문서\공부\ryang_python_practice\part.3\Data\실습5_ 교통 데이터를 활용한 지리 데이터 시각화\서울시 역사마스터 정보.csv", encoding='cp949')
coordinate = coordinate.query('호선 == "2호선"')
station_list = ['신대방', '신림', '봉천', '서울대입구(관악구청)', '낙성대', '사당']
coordinate.query('역사명 in @station_list')

     역사_ID          역사명   호선         위도          경도
727    231          신대방  2호선  37.487462  126.913149
728    230           신림  2호선  37.484201  126.929715
729    229           봉천  2호선  37.482362  126.941892
730    228  서울대입구(관악구청)  2호선  37.481247  126.952739
731    227          낙성대  2호선  37.476930  126.963693
732    226           사당  2호선  37.476538  126.981544

In [ ]:
pip install haversine #위경도 거리 재는 라이브러리

Collecting haversine
  Downloading haversine-2.9.0-py2.py3-none-any.whl.metadata (5.8 kB)
Downloading haversine-2.9.0-py2.py3-none-any.whl (7.7 kB)
Installing collected packages: haversine
Successfully installed haversine-2.9.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:
from haversine import haversine

haversine((37.487462,126.913149), (37.484201,126.929715), unit = 'm')

1505.9854014218404

In [40]:
def distance(station_name, lat, long):
    station_lat = coordinate.query(f'역사명 == "{station_name}"')['위도'].values[0]
    station_long = coordinate.query(f'역사명 == "{station_name}"')['경도'].values[0]

    distance = haversine((station_lat, station_long), (lat, long), unit = 'm')

    return distance

In [41]:
distance('신림', 37.479689, 126.939191)

975.1183098085165

In [44]:
data_filtered.apply(lambda x: distance('신림', x['위도'], x['경도']), axis=1)

0        975.118310
3       3175.659902
8        300.127317
10      2039.012421
14      1737.376094
           ...
1985    3241.244214
1986    4344.707045
1988    1118.839557
1989    1577.096734
1995    2929.138426
Length: 823, dtype: float64

In [42]:
for s in station_list:
    data_filtered[s] = data_filtered.apply(lambda x: distance(s, x['위도'], x['경도']), axis=1)

In [45]:
data_filtered.head()

,물건번호,월세,보증금,전용면적(m2),방향,위도,경도,물건층,전체층,연식,신대방,신림,봉천,서울대입구(관악구청),낙성대,사당
0,2339667467,55,1000,19.80,남서향,37.479689,126.939191,2,4,None,2455.029924,975.118310,380.980006,1207.963739,2183.777211,3753.736839
3,2339568890,40,1000,16.00,서향,37.478551,126.964993,2,5,None,4680.643219,3175.659902,2082.015638,1122.088696,213.655993,1477.571074
8,2339681933,45,300,16.52,서향,37.486020,126.927202,3,6,None,1250.257936,300.127317,1358.504444,2314.951110,3374.841720,4909.637223
10,2339663561,35,500,19.80,서향,37.484998,126.952802,저,4,None,3509.424691,2039.012421,1006.291894,417.129788,1314.678540,2705.027412
14,2339661926,50,1000,19.80,동향,37.484270,126.949405,저,4,None,3218.630513,1737.376094,696.044484,446.694269,1501.892777,2963.409925

In [46]:
data_filtered['역까지최소거리'] = data_filtered.apply(lambda x: min([x['신대방'], x['신림'], x['봉천'], x['서울대입구(관악구청)'], x['낙성대'], x['사당']]), axis=1)
data_filtered.head()

,물건번호,월세,보증금,전용면적(m2),방향,위도,경도,물건층,전체층,연식,신대방,신림,봉천,서울대입구(관악구청),낙성대,사당,역까지최소거리
0,2339667467,55,1000,19.80,남서향,37.479689,126.939191,2,4,None,2455.029924,975.118310,380.980006,1207.963739,2183.777211,3753.736839,380.980006
3,2339568890,40,1000,16.00,서향,37.478551,126.964993,2,5,None,4680.643219,3175.659902,2082.015638,1122.088696,213.655993,1477.571074,213.655993
8,2339681933,45,300,16.52,서향,37.486020,126.927202,3,6,None,1250.257936,300.127317,1358.504444,2314.951110,3374.841720,4909.637223,300.127317
10,2339663561,35,500,19.80,서향,37.484998,126.952802,저,4,None,3509.424691,2039.012421,1006.291894,417.129788,1314.678540,2705.027412,417.129788
14,2339661926,50,1000,19.80,동향,37.484270,126.949405,저,4,None,3218.630513,1737.376094,696.044484,446.694269,1501.892777,2963.409925,446.694269

In [47]:
data_filtered.drop(station_list, axis=1, inplace=True)
data_filtered.head()

,물건번호,월세,보증금,전용면적(m2),방향,위도,경도,물건층,전체층,연식,역까지최소거리
0,2339667467,55,1000,19.80,남서향,37.479689,126.939191,2,4,None,380.980006
3,2339568890,40,1000,16.00,서향,37.478551,126.964993,2,5,None,213.655993
8,2339681933,45,300,16.52,서향,37.486020,126.927202,3,6,None,300.127317
10,2339663561,35,500,19.80,서향,37.484998,126.952802,저,4,None,417.129788
14,2339661926,50,1000,19.80,동향,37.484270,126.949405,저,4,None,446.694269

## **분석**

- 각 항목 분포 확인하기

In [48]:
for x in ['월세','보증금','전용면적(m2)','연식','역까지최소거리']:
    fig = px.box(data_frame = data_filtered, x=x, width=700, height=400)
    fig.show()

- 내가 원하는 조건은?
    - 보증금 3000만원 이하 ✅
    - 월세는 저렴할수록 좋음
    - 지하, 반지하, 꼭대기층은 선호하지 않음 ✅
    - 전용면적이 클수록 좋음
    - 북향은 선호하지 않음 ✅
    - 연식이 오래되지 않을수록 좋음
    - 지하철 역에서 가까울수록 좋음

- 월세, 전용면적, 연식, 지하철역까지의 거리 점수 매기기

In [49]:
data_filtered

,물건번호,월세,보증금,전용면적(m2),방향,위도,경도,물건층,전체층,연식,역까지최소거리
0,2339667467,55,1000,19.80,남서향,37.479689,126.939191,2,4,None,380.980006
3,2339568890,40,1000,16.00,서향,37.478551,126.964993,2,5,None,213.655993
8,2339681933,45,300,16.52,서향,37.486020,126.927202,3,6,None,300.127317
10,2339663561,35,500,19.80,서향,37.484998,126.952802,저,4,None,417.129788
14,2339661926,50,1000,19.80,동향,37.484270,126.949405,저,4,None,446.694269
...,...,...,...,...,...,...,...,...,...,...,...
1985,2339185628,100,2000,39.67,남동향,37.473537,126.963900,중,4,None,377.726864
1986,2339175088,40,500,21.00,남동향,37.474253,126.977329,저,3,None,450.454340
1988,2339199717,45,500,21.49,남동향,37.475558,126.936207,고,4,None,907.776276
1989,2339203612,90,2000,45.60,서향,37.472359,126.919879,3,5,None,1577.096734
1995,2339187707,35,300,19.84,남동향,37.478363,126.962085,3,4,None,213.364348

In [56]:
print(data_filtered['연식'].unique())
print(data_filtered['연식'].describe())

[0]
count    823.0
mean       0.0
std        0.0
min        0.0
25%        0.0
50%        0.0
75%        0.0
max        0.0
Name: 연식, dtype: float64

In [ ]:
## 연식에 0.0들이 있어서 등급화가 안됨.
## 연식이 0.0이 아닌 경우에만 등급화하기
if len(data_filtered['연식'].unique()) > 1:
    data_filtered['연식_등급'] = pd.qcut(data_filtered['연식'], 5, labels=[1, 2, 3, 4, 5])
else:
    data_filtered['연식_등급'] = 1  # 모두 0.0이므로 1로 통일

In [71]:
data_filtered['월세_등급'] = pd.qcut(data_filtered['월세'], 5, labels=[1,2,3,4,5])
data_filtered['전용면적_등급'] = pd.qcut(data_filtered['전용면적(m2)'], 5, labels=[5,4,3,2,1])

## 연식에 0.0들이 있어서 등급화가 안됨.
## 연식이 0.0이 아닌 경우에만 등급화하기
if len(data_filtered['연식'].unique()) > 1:
    data_filtered['연식_등급'] = pd.qcut(data_filtered['연식'], 5, labels=[1, 2, 3, 4, 5])
else:
    data_filtered['연식_등급'] = 1  # 모두 0.0이므로 1로 통일

data_filtered['연식_등급'] = pd.qcut(data_filtered['연식'].rank(method='first'), 5, labels=[1,2,3,4,5])
data_filtered['역까지최소거리_등급'] = pd.qcut(data_filtered['역까지최소거리'], 5, labels=[1,2,3,4,5])

In [72]:
data_filtered

,물건번호,월세,보증금,전용면적(m2),방향,위도,경도,물건층,전체층,연식,역까지최소거리,월세_등급,전용면적_등급,연식_등급,역까지최소거리_등급
0,2339667467,55,1000,19.80,남서향,37.479689,126.939191,2,4,0,380.980006,4,4,1,2
3,2339568890,40,1000,16.00,서향,37.478551,126.964993,2,5,0,213.655993,2,5,1,1
8,2339681933,45,300,16.52,서향,37.486020,126.927202,3,6,0,300.127317,2,5,1,2
10,2339663561,35,500,19.80,서향,37.484998,126.952802,저,4,0,417.129788,1,4,1,3
14,2339661926,50,1000,19.80,동향,37.484270,126.949405,저,4,0,446.694269,3,4,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1985,2339185628,100,2000,39.67,남동향,37.473537,126.963900,중,4,0,377.726864,5,1,5,2
1986,2339175088,40,500,21.00,남동향,37.474253,126.977329,저,3,0,450.454340,2,3,5,3
1988,2339199717,45,500,21.49,남동향,37.475558,126.936207,고,4,0,907.776276,2,2,5,5
1989,2339203612,90,2000,45.60,서향,37.472359,126.919879,3,5,0,1577.096734,5,1,5,5
1995,2339187707,35,300,19.84,남동향,37.478363,126.962085,3,4,0,213.364348,1,3,5,1

In [65]:
print(data_filtered['전용면적(m2)'].unique())
print(data_filtered['전용면적(m2)'].describe())

[19.8  16.   16.52 23.1  18.1  19.2  18.   19.9  17.25 22.   16.5  18.2
 37.82 13.22 20.   14.72 17.   20.13 31.   21.84 19.   19.83 28.37 13.59
 46.28 16.53 17.57 18.18 15.   16.73 40.8  29.75 16.2  35.   39.67 56.01
 19.84 24.   26.4  33.   38.88 13.11 23.   10.   17.16 49.35 18.13 18.54
 23.14 39.66  0.   30.   42.47 19.12 25.   36.15 16.44 27.   20.86 26.
 33.06 36.37 21.49 24.7  20.3  30.1  14.64 21.   16.38 17.13 29.7  29.54
 28.   24.8  13.31 17.01 16.77 17.91 14.79 21.48 20.4  33.1  17.9  23.23
 51.17 26.45 14.4  14.74 24.98 29.57  8.   18.05 37.92 11.8  43.51 30.8
 40.5  24.53 21.4  20.8  17.32 14.24 15.31 17.35 29.98 19.1  21.47 41.88
 23.04 21.34 14.89 13.02 29.99 23.2  49.59 28.09 26.95 14.01 13.05 14.87
 19.5  16.64 28.29 19.11 18.15 12.62 23.47 27.06 25.33 23.33 57.26 17.69
 24.75 30.24 24.08 27.67 33.05 14.6  40.64 29.83 34.5  15.84 29.9  16.3
 14.21 21.5  16.6  26.46  6.   40.   29.1  24.5  99.18 24.77 20.5  30.88
 29.94 36.36 27.44 15.9  13.23 39.   17.6  19.62 25.4  25.2  13.86 22.78
 26.44 28.1  38.17 16.18 27.65 15.2  10.92 16.32 13.6  13.08 17.14 16.9
 40.72 29.5  18.74 17.54 22.41 38.   13.8  47.   40.83 27.47 45.6 ]
count    823.000000
mean      21.828651
std        7.144662
min        0.000000
25%       18.000000
50%       19.830000
75%       23.100000
max       99.180000
Name: 전용면적(m2), dtype: float64

In [67]:
# 0.0 값을 NaN으로 대체
data_filtered['전용면적(m2)'] = data_filtered['전용면적(m2)'].replace(0, np.nan)

# NaN이 아닌 값만 qcut()에 사용
data_filtered['전용면적_등급'] = pd.qcut(data_filtered['전용면적(m2)'].dropna(), 5, labels=[5, 4, 3, 2, 1])

In [68]:
print(data_filtered[['전용면적(m2)', '전용면적_등급']].head(20))

    전용면적(m2) 전용면적_등급
0      19.80       4
3      16.00       5
8      16.52       5
10     19.80       4
14     19.80       4
15     23.10       2
16     23.10       2
18     19.80       4
19     23.10       2
20     18.10       4
22     19.80       4
25     19.20       4
26     18.00       4
27     23.10       2
29     19.90       3
31     23.10       2
32     19.80       4
38     17.25       4
39     22.00       2
40     19.80       4

In [69]:
print(data_filtered[['전용면적(m2)', '전용면적_등급']].head(10))

    전용면적(m2) 전용면적_등급
0      19.80       4
3      16.00       5
8      16.52       5
10     19.80       4
14     19.80       4
15     23.10       2
16     23.10       2
18     19.80       4
19     23.10       2
20     18.10       4

In [73]:
data_filtered_final = data_filtered.query('월세_등급 <= 3 and 전용면적_등급 <= 1 and 연식_등급 <= 2 and 역까지최소거리_등급 <= 2')
data_filtered_final

,물건번호,월세,보증금,전용면적(m2),방향,위도,경도,물건층,전체층,연식,역까지최소거리,월세_등급,전용면적_등급,연식_등급,역까지최소거리_등급
3,2339568890,40,1000,16.00,서향,37.478551,126.964993,2,5,0,213.655993,2,5,1,1
8,2339681933,45,300,16.52,서향,37.486020,126.927202,3,6,0,300.127317,2,5,1,2
15,2339672283,45,3000,23.10,남동향,37.484725,126.927215,7,12,0,228.153838,2,2,1,1
16,2339666010,43,500,23.10,남향,37.483269,126.932413,저,3,0,259.640397,2,2,1,1
19,2339683991,35,1000,23.10,남서향,37.485205,126.940495,중,3,0,339.309811,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814,2339959412,40,500,17.90,남서향,37.482961,126.930678,2,4,0,161.961715,2,4,2,1
820,2339945467,40,3000,19.84,남동향,37.481106,126.945038,중,8,0,310.750930,2,3,2,2
821,2339929044,45,1000,23.10,동향,37.475617,126.964569,2,4,0,165.201228,2,2,2,1
834,2339931451,50,1000,16.53,남향,37.480698,126.948689,저,10,0,362.546299,3,5,2,2
837,2339928778,50,500,23.23,동향,37.480379,126.944074,중,10,0,292.730018,3,1,2,2

- 최종 매물 리스트 시각화

In [74]:
f = folium.Figure(width=700, height=500)
m = folium.Map(location=[37.486313, 126.935378], zoom_start=14).add_to(f)

for idx in data_filtered_final.index:
    lat = data_filtered_final.loc[idx, '위도']
    long = data_filtered_final.loc[idx, '경도']
    num = data_filtered_final.loc[idx, '물건번호']

    folium.Marker([lat, long]
                  , popup=f"<a href=https://m.land.naver.com/article/info/{num}>링크</a>"
                  ).add_to(m)
m