# **영화 데이터 - 영화 흥행 요인 분석**

## **데이터 살펴보기**

In [4]:
import pandas as pd

In [38]:
movies = pd.read_csv('/content/drive/MyDrive/강의자료_황수현_Python/Part3) 파이썬 데이터 분석 프로젝트/data/실습2: 영화 데이터를 활용한 영화 흥행 요인 분석/tmdb_5000_movies.csv')
movies.head()

OSError: [Errno 22] Invalid argument: '/content/drive/MyDrive/강의자료_황수현_Python/Part3) 파이썬 데이터 분석 프로젝트/data/실습2: 영화 데이터를 활용한 영화 흥행 요인 분석/tmdb_5000_movies.csv'

In [6]:
movies = pd.read_csv(r"C:\Users\ryang\OneDrive\문서\공부\ryang_python_practice\part.3\Data\실습2_ 영화 데이터를 활용한 영화 흥행 요인 분석\tmdb_5000_movies.csv")
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [7]:
credits = pd.read_csv(r"C:\Users\ryang\OneDrive\문서\공부\ryang_python_practice\part.3\Data\실습2_ 영화 데이터를 활용한 영화 흥행 요인 분석\tmdb_5000_credits.csv")
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

**movies 데이터**
- budget: 영화 예산 (단위: 달러)
- genres: 모든 장르
- homepage: 공식 홈페이지
- id: 각 영화당 unique id
- original_language: 원 언어
- original_title: 원 제목
- overview: 간략한 설명
- popularity: TMDB에서 제공하는 인기도
- production_companies: 모든 제작사
- production_countries: 모든 제각국가
- release_date: 개봉일
- revenue: 흥행 수익 (단위: 달러)
- runtime: 상영 시간
- spoken_language: 사용된 모든 언어
- status: 개봉 여부
- title: 영문 제목
- vote_avearage: TMDB에서 받은 평점 평균
- vote_count: TMDB에서 받은 투표수

**credits 데이터**
- movie_id: 각 영화당 unique id
- title: 영문 제목
- cast: 모든 출연진
- crew: 모든 제작진

## **질문 만들기**
- 연도별 흥행 수익은?
- 가장 흥행한 영화 TOP 10은?
- 흥행에 가장 성공한 감독과 배우는?
- 장르와 흥행 수익
    - 흥행 수익이 좋은 장르는?
    - 시간의 흐름에 따라 유행하는 장르가 바뀌는가?
    - 월별로 흥행하는 장르가 있는가?
- 수익과 예산, 투표수, 평점과의 상관관계는?
- ROI(예산 대비 수익)가 높으면서 흥행에 성공한 영화의 특징은?

## **데이터 전처리**

- 필요한 컬럼만 남기기

In [8]:
movies_df = movies[['id','budget','genres','title','release_date','revenue','vote_average','vote_count']]
credits_df = credits[['movie_id','crew','cast']]

- 데이터 결합

In [9]:
data = pd.merge(movies_df, credits_df, left_on = 'id', right_on = 'movie_id').drop('movie_id', axis=1)  ## movie_id는 필요없으니 drop. 열 삭제할때는 axis=1
data.head()

,id,budget,genres,title,release_date,revenue,vote_average,vote_count,crew,cast
0,19995,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,2009-12-10,2787965087,7.2,11800,"[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""..."
1,285,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,2007-05-19,961000000,6.9,4500,"[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa..."
2,206647,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,2015-10-26,880674609,6.3,4466,"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr..."
3,49026,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,2012-07-16,1084939099,7.6,9106,"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba..."
4,49529,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,2012-03-07,284139100,6.1,2124,"[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c..."

- roi 컬럼 만들기

In [10]:
data['roi'] = data['revenue'] / data['budget']
data.head()

,id,budget,genres,title,release_date,revenue,vote_average,vote_count,crew,cast,roi
0,19995,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,2009-12-10,2787965087,7.2,11800,"[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",11.763566
1,285,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,2007-05-19,961000000,6.9,4500,"[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",3.203333
2,206647,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,2015-10-26,880674609,6.3,4466,"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",3.594590
3,49026,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,2012-07-16,1084939099,7.6,9106,"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",4.339756
4,49529,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,2012-03-07,284139100,6.1,2124,"[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",1.092843

- 감독 컬럼 만들기

In [11]:
data['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [12]:
import ast

print(ast.literal_eval(data['crew'][0]))  ## 문자열을 리스트로 변환환

[{'credit_id': '52fe48009251416c750aca23', 'department': 'Editing', 'gender': 0, 'id': 1721, 'job': 'Editor', 'name': 'Stephen E. Rivkin'}, {'credit_id': '539c47ecc3a36810e3001f87', 'department': 'Art', 'gender': 2, 'id': 496, 'job': 'Production Design', 'name': 'Rick Carter'}, {'credit_id': '54491c89c3a3680fb4001cf7', 'department': 'Sound', 'gender': 0, 'id': 900, 'job': 'Sound Designer', 'name': 'Christopher Boyes'}, {'credit_id': '54491cb70e0a267480001bd0', 'department': 'Sound', 'gender': 0, 'id': 900, 'job': 'Supervising Sound Editor', 'name': 'Christopher Boyes'}, {'credit_id': '539c4a4cc3a36810c9002101', 'department': 'Production', 'gender': 1, 'id': 1262, 'job': 'Casting', 'name': 'Mali Finn'}, {'credit_id': '5544ee3b925141499f0008fc', 'department': 'Sound', 'gender': 2, 'id': 1729, 'job': 'Original Music Composer', 'name': 'James Horner'}, {'credit_id': '52fe48009251416c750ac9c3', 'department': 'Directing', 'gender': 2, 'id': 2710, 'job': 'Director', 'name': 'James Cameron'}, {'credit_id': '52fe48009251416c750ac9d9', 'department': 'Writing', 'gender': 2, 'id': 2710, 'job': 'Writer', 'name': 'James Cameron'}, {'credit_id': '52fe48009251416c750aca17', 'department': 'Editing', 'gender': 2, 'id': 2710, 'job': 'Editor', 'name': 'James Cameron'}, {'credit_id': '52fe48009251416c750aca29', 'department': 'Production', 'gender': 2, 'id': 2710, 'job': 'Producer', 'name': 'James Cameron'}, {'credit_id': '52fe48009251416c750aca3f', 'department': 'Writing', 'gender': 2, 'id': 2710, 'job': 'Screenplay', 'name': 'James Cameron'}, {'credit_id': '539c4987c3a36810ba0021a4', 'department': 'Art', 'gender': 2, 'id': 7236, 'job': 'Art Direction', 'name': 'Andrew Menzies'}, {'credit_id': '549598c3c3a3686ae9004383', 'department': 'Visual Effects', 'gender': 0, 'id': 6690, 'job': 'Visual Effects Producer', 'name': 'Jill Brooks'}, {'credit_id': '52fe48009251416c750aca4b', 'department': 'Production', 'gender': 1, 'id': 6347, 'job': 'Casting', 'name': 'Margery Simkin'}, {'credit_id': '570b6f419251417da70032fe', 'department': 'Art', 'gender': 2, 'id': 6878, 'job': 'Supervising Art Director', 'name': 'Kevin Ishioka'}, {'credit_id': '5495a0fac3a3686ae9004468', 'department': 'Sound', 'gender': 0, 'id': 6883, 'job': 'Music Editor', 'name': 'Dick Bernstein'}, {'credit_id': '54959706c3a3686af3003e81', 'department': 'Sound', 'gender': 0, 'id': 8159, 'job': 'Sound Effects Editor', 'name': 'Shannon Mills'}, {'credit_id': '54491d58c3a3680fb1001ccb', 'department': 'Sound', 'gender': 0, 'id': 8160, 'job': 'Foley', 'name': 'Dennie Thorpe'}, {'credit_id': '54491d6cc3a3680fa5001b2c', 'department': 'Sound', 'gender': 0, 'id': 8163, 'job': 'Foley', 'name': 'Jana Vance'}, {'credit_id': '52fe48009251416c750aca57', 'department': 'Costume & Make-Up', 'gender': 1, 'id': 8527, 'job': 'Costume Design', 'name': 'Deborah Lynn Scott'}, {'credit_id': '52fe48009251416c750aca2f', 'department': 'Production', 'gender': 2, 'id': 8529, 'job': 'Producer', 'name': 'Jon Landau'}, {'credit_id': '539c4937c3a36810ba002194', 'department': 'Art', 'gender': 0, 'id': 9618, 'job': 'Art Direction', 'name': 'Sean Haworth'}, {'credit_id': '539c49b6c3a36810c10020e6', 'department': 'Art', 'gender': 1, 'id': 12653, 'job': 'Set Decoration', 'name': 'Kim Sinclair'}, {'credit_id': '570b6f2f9251413a0e00020d', 'department': 'Art', 'gender': 1, 'id': 12653, 'job': 'Supervising Art Director', 'name': 'Kim Sinclair'}, {'credit_id': '54491a6c0e0a26748c001b19', 'department': 'Art', 'gender': 2, 'id': 14350, 'job': 'Set Designer', 'name': 'Richard F. Mays'}, {'credit_id': '56928cf4c3a3684cff0025c4', 'department': 'Production', 'gender': 1, 'id': 20294, 'job': 'Executive Producer', 'name': 'Laeta Kalogridis'}, {'credit_id': '52fe48009251416c750aca51', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 17675, 'job': 'Costume Design', 'name': 'Mayes C. Rubeo'}, {'credit_id': '52fe48009251416c750aca11', 'department': 'Camera', 'gender': 2, 'id': 18265, 'job': 'Director of Photography', 'name': 'Mauro Fiore'}, {'credit_id': '5449194d0e0a26748f001b39', 'department': 'Art', 'gender': 0, 'id': 42281, 'job': 'Set Designer', 'name': 'Scott Herbertson'}, {'credit_id': '52fe48009251416c750aca05', 'department': 'Crew', 'gender': 0, 'id': 42288, 'job': 'Stunts', 'name': 'Woody Schultz'}, {'credit_id': '5592aefb92514152de0010f5', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 29067, 'job': 'Makeup Artist', 'name': 'Linda DeVetta'}, {'credit_id': '5592afa492514152de00112c', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 29067, 'job': 'Hairstylist', 'name': 'Linda DeVetta'}, {'credit_id': '54959ed592514130fc002e5d', 'department': 'Camera', 'gender': 2, 'id': 33302, 'job': 'Camera Operator', 'name': 'Richard Bluck'}, {'credit_id': '539c4891c3a36810ba002147', 'department': 'Art', 'gender': 2, 'id': 33303, 'job': 'Art Direction', 'name': 'Simon Bright'}, {'credit_id': '54959c069251417a81001f3a', 'department': 'Visual Effects', 'gender': 0, 'id': 113145, 'job': 'Visual Effects Supervisor', 'name': 'Richard Martin'}, {'credit_id': '54959a0dc3a3680ff5002c8d', 'department': 'Crew', 'gender': 2, 'id': 58188, 'job': 'Visual Effects Editor', 'name': 'Steve R. Moore'}, {'credit_id': '52fe48009251416c750aca1d', 'department': 'Editing', 'gender': 2, 'id': 58871, 'job': 'Editor', 'name': 'John Refoua'}, {'credit_id': '54491a4dc3a3680fc30018ca', 'department': 'Art', 'gender': 0, 'id': 92359, 'job': 'Set Designer', 'name': 'Karl J. Martin'}, {'credit_id': '52fe48009251416c750aca35', 'department': 'Camera', 'gender': 1, 'id': 72201, 'job': 'Director of Photography', 'name': 'Chiling Lin'}, {'credit_id': '52fe48009251416c750ac9ff', 'department': 'Crew', 'gender': 0, 'id': 89714, 'job': 'Stunts', 'name': 'Ilram Choi'}, {'credit_id': '54959c529251416e2b004394', 'department': 'Visual Effects', 'gender': 2, 'id': 93214, 'job': 'Visual Effects Supervisor', 'name': 'Steven Quale'}, {'credit_id': '54491edf0e0a267489001c37', 'department': 'Crew', 'gender': 1, 'id': 122607, 'job': 'Dialect Coach', 'name': 'Carla Meyer'}, {'credit_id': '539c485bc3a368653d001a3a', 'department': 'Art', 'gender': 2, 'id': 132585, 'job': 'Art Direction', 'name': 'Nick Bassett'}, {'credit_id': '539c4903c3a368653d001a74', 'department': 'Art', 'gender': 0, 'id': 132596, 'job': 'Art Direction', 'name': 'Jill Cormack'}, {'credit_id': '539c4967c3a368653d001a94', 'department': 'Art', 'gender': 0, 'id': 132604, 'job': 'Art Direction', 'name': 'Andy McLaren'}, {'credit_id': '52fe48009251416c750aca45', 'department': 'Crew', 'gender': 0, 'id': 236696, 'job': 'Motion Capture Artist', 'name': 'Terry Notary'}, {'credit_id': '54959e02c3a3680fc60027d2', 'department': 'Crew', 'gender': 2, 'id': 956198, 'job': 'Stunt Coordinator', 'name': 'Garrett Warren'}, {'credit_id': '54959ca3c3a3686ae300438c', 'department': 'Visual Effects', 'gender': 2, 'id': 957874, 'job': 'Visual Effects Supervisor', 'name': 'Jonathan Rothbart'}, {'credit_id': '570b6f519251412c74001b2f', 'department': 'Art', 'gender': 0, 'id': 957889, 'job': 'Supervising Art Director', 'name': 'Stefan Dechant'}, {'credit_id': '570b6f62c3a3680b77007460', 'department': 'Art', 'gender': 2, 'id': 959555, 'job': 'Supervising Art Director', 'name': 'Todd Cherniawsky'}, {'credit_id': '539c4a3ac3a36810da0021cc', 'department': 'Production', 'gender': 0, 'id': 1016177, 'job': 'Casting', 'name': 'Miranda Rivers'}, {'credit_id': '539c482cc3a36810c1002062', 'department': 'Art', 'gender': 0, 'id': 1032536, 'job': 'Production Design', 'name': 'Robert Stromberg'}, {'credit_id': '539c4b65c3a36810c9002125', 'department': 'Costume & Make-Up', 'gender': 2, 'id': 1071680, 'job': 'Costume Design', 'name': 'John Harding'}, {'credit_id': '54959e6692514130fc002e4e', 'department': 'Camera', 'gender': 0, 'id': 1177364, 'job': 'Steadicam Operator', 'name': 'Roberto De Angelis'}, {'credit_id': '539c49f1c3a368653d001aac', 'department': 'Costume & Make-Up', 'gender': 2, 'id': 1202850, 'job': 'Makeup Department Head', 'name': 'Mike Smithson'}, {'credit_id': '5495999ec3a3686ae100460c', 'department': 'Visual Effects', 'gender': 0, 'id': 1204668, 'job': 'Visual Effects Producer', 'name': 'Alain Lalanne'}, {'credit_id': '54959cdfc3a3681153002729', 'department': 'Visual Effects', 'gender': 0, 'id': 1206410, 'job': 'Visual Effects Supervisor', 'name': 'Lucas Salton'}, {'credit_id': '549596239251417a81001eae', 'department': 'Crew', 'gender': 0, 'id': 1234266, 'job': 'Post Production Supervisor', 'name': 'Janace Tashjian'}, {'credit_id': '54959c859251416e1e003efe', 'department': 'Visual Effects', 'gender': 0, 'id': 1271932, 'job': 'Visual Effects Supervisor', 'name': 'Stephen Rosenbaum'}, {'credit_id': '5592af28c3a368775a00105f', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 1310064, 'job': 'Makeup Artist', 'name': 'Frankie Karena'}, {'credit_id': '539c4adfc3a36810e300203b', 'department': 'Costume & Make-Up', 'gender': 1, 'id': 1319844, 'job': 'Costume Supervisor', 'name': 'Lisa Lovaas'}, {'credit_id': '54959b579251416e2b004371', 'department': 'Visual Effects', 'gender': 0, 'id': 1327028, 'job': 'Visual Effects Supervisor', 'name': 'Jonathan Fawkner'}, {'credit_id': '539c48a7c3a36810b5001fa7', 'department': 'Art', 'gender': 0, 'id': 1330561, 'job': 'Art Direction', 'name': 'Robert Bavin'}, {'credit_id': '539c4a71c3a36810da0021e0', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 1330567, 'job': 'Costume Supervisor', 'name': 'Anthony Almaraz'}, {'credit_id': '539c4a8ac3a36810ba0021e4', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 1330570, 'job': 'Costume Supervisor', 'name': 'Carolyn M. Fenton'}, {'credit_id': '539c4ab6c3a36810da0021f0', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 1330574, 'job': 'Costume Supervisor', 'name': 'Beth Koenigsberg'}, {'credit_id': '54491ab70e0a267480001ba2', 'department': 'Art', 'gender': 0, 'id': 1336191, 'job': 'Set Designer', 'name': 'Sam Page'}, {'credit_id': '544919d9c3a3680fc30018bd', 'department': 'Art', 'gender': 0, 'id': 1339441, 'job': 'Set Designer', 'name': 'Tex Kadonaga'}, {'credit_id': '54491cf50e0a267483001b0c', 'department': 'Editing', 'gender': 0, 'id': 1352422, 'job': 'Dialogue Editor', 'name': 'Kim Foscato'}, {'credit_id': '544919f40e0a26748c001b09', 'department': 'Art', 'gender': 0, 'id': 1352962, 'job': 'Set Designer', 'name': 'Tammy S. Lee'}, {'credit_id': '5495a115c3a3680ff5002d71', 'department': 'Crew', 'gender': 0, 'id': 1357070, 'job': 'Transportation Coordinator', 'name': 'Denny Caira'}, {'credit_id': '5495a12f92514130fc002e94', 'department': 'Crew', 'gender': 0, 'id': 1357071, 'job': 'Transportation Coordinator', 'name': 'James Waitkus'}, {'credit_id': '5495976fc3a36811530026b0', 'department': 'Sound', 'gender': 0, 'id': 1360103, 'job': 'Supervising Sound Editor', 'name': 'Addison Teague'}, {'credit_id': '54491837c3a3680fb1001c5a', 'department': 'Art', 'gender': 2, 'id': 1376887, 'job': 'Set Designer', 'name': 'C. Scott Baker'}, {'credit_id': '54491878c3a3680fb4001c9d', 'department': 'Art', 'gender': 0, 'id': 1376888, 'job': 'Set Designer', 'name': 'Luke Caska'}, {'credit_id': '544918dac3a3680fa5001ae0', 'department': 'Art', 'gender': 0, 'id': 1376889, 'job': 'Set Designer', 'name': 'David Chow'}, {'credit_id': '544919110e0a267486001b68', 'department': 'Art', 'gender': 0, 'id': 1376890, 'job': 'Set Designer', 'name': 'Jonathan Dyer'}, {'credit_id': '54491967c3a3680faa001b5e', 'department': 'Art', 'gender': 0, 'id': 1376891, 'job': 'Set Designer', 'name': 'Joseph Hiura'}, {'credit_id': '54491997c3a3680fb1001c8a', 'department': 'Art', 'gender': 0, 'id': 1376892, 'job': 'Art Department Coordinator', 'name': 'Rebecca Jellie'}, {'credit_id': '544919ba0e0a26748f001b42', 'department': 'Art', 'gender': 0, 'id': 1376893, 'job': 'Set Designer', 'name': 'Robert Andrew Johnson'}, {'credit_id': '54491b1dc3a3680faa001b8c', 'department': 'Art', 'gender': 0, 'id': 1376895, 'job': 'Assistant Art Director', 'name': 'Mike Stassi'}, {'credit_id': '54491b79c3a3680fbb001826', 'department': 'Art', 'gender': 0, 'id': 1376897, 'job': 'Construction Coordinator', 'name': 'John Villarino'}, {'credit_id': '54491baec3a3680fb4001ce6', 'department': 'Art', 'gender': 2, 'id': 1376898, 'job': 'Assistant Art Director', 'name': 'Jeffrey Wisniewski'}, {'credit_id': '54491d2fc3a3680fb4001d07', 'department': 'Editing', 'gender': 0, 'id': 1376899, 'job': 'Dialogue Editor', 'name': 'Cheryl Nardi'}, {'credit_id': '54491d86c3a3680fa5001b2f', 'department': 'Editing', 'gender': 0, 'id': 1376901, 'job': 'Dialogue Editor', 'name': 'Marshall Winn'}, {'credit_id': '54491d9dc3a3680faa001bb0', 'department': 'Sound', 'gender': 0, 'id': 1376902, 'job': 'Supervising Sound Editor', 'name': 'Gwendolyn Yates Whittle'}, {'credit_id': '54491dc10e0a267486001bce', 'department': 'Sound', 'gender': 0, 'id': 1376903, 'job': 'Sound Re-Recording Mixer', 'name': 'William Stein'}, {'credit_id': '54491f500e0a26747c001c07', 'department': 'Crew', 'gender': 0, 'id': 1376909, 'job': 'Choreographer', 'name': 'Lula Washington'}, {'credit_id': '549599239251412c4e002a2e', 'department': 'Visual Effects', 'gender': 0, 'id': 1391692, 'job': 'Visual Effects Producer', 'name': 'Chris Del Conte'}, {'credit_id': '54959d54c3a36831b8001d9a', 'department': 'Visual Effects', 'gender': 2, 'id': 1391695, 'job': 'Visual Effects Supervisor', 'name': 'R. Christopher White'}, {'credit_id': '54959bdf9251412c4e002a66', 'department': 'Visual Effects', 'gender': 0, 'id': 1394070, 'job': 'Visual Effects Supervisor', 'name': 'Dan Lemmon'}, {'credit_id': '5495971d92514132ed002922', 'department': 'Sound', 'gender': 0, 'id': 1394129, 'job': 'Sound Effects Editor', 'name': 'Tim Nielsen'}, {'credit_id': '5592b25792514152cc0011aa', 'department': 'Crew', 'gender': 0, 'id': 1394286, 'job': 'CG Supervisor', 'name': 'Michael Mulholland'}, {'credit_id': '54959a329251416e2b004355', 'department': 'Crew', 'gender': 0, 'id': 1394750, 'job': 'Visual Effects Editor', 'name': 'Thomas Nittmann'}, {'credit_id': '54959d6dc3a3686ae9004401', 'department': 'Visual Effects', 'gender': 0, 'id': 1394755, 'job': 'Visual Effects Supervisor', 'name': 'Edson Williams'}, {'credit_id': '5495a08fc3a3686ae300441c', 'department': 'Editing', 'gender': 0, 'id': 1394953, 'job': 'Digital Intermediate', 'name': 'Christine Carr'}, {'credit_id': '55402d659251413d6d000249', 'department': 'Visual Effects', 'gender': 0, 'id': 1395269, 'job': 'Visual Effects Supervisor', 'name': 'John Bruno'}, {'credit_id': '54959e7b9251416e1e003f3e', 'department': 'Camera', 'gender': 0, 'id': 1398970, 'job': 'Steadicam Operator', 'name': 'David Emmerichs'}, {'credit_id': '54959734c3a3686ae10045e0', 'department': 'Sound', 'gender': 0, 'id': 1400906, 'job': 'Sound Effects Editor', 'name': 'Christopher Scarabosio'}, {'credit_id': '549595dd92514130fc002d79', 'department': 'Production', 'gender': 0, 'id': 1401784, 'job': 'Production Supervisor', 'name': 'Jennifer Teves'}, {'credit_id': '549596009251413af70028cc', 'department': 'Production', 'gender': 0, 'id': 1401785, 'job': 'Production Manager', 'name': 'Brigitte Yorke'}, {'credit_id': '549596e892514130fc002d99', 'department': 'Sound', 'gender': 0, 'id': 1401786, 'job': 'Sound Effects Editor', 'name': 'Ken Fischer'}, {'credit_id': '549598229251412c4e002a1c', 'department': 'Crew', 'gender': 0, 'id': 1401787, 'job': 'Special Effects Coordinator', 'name': 'Iain Hutton'}, {'credit_id': '549598349251416e2b00432b', 'department': 'Crew', 'gender': 0, 'id': 1401788, 'job': 'Special Effects Coordinator', 'name': 'Steve Ingram'}, {'credit_id': '54959905c3a3686ae3004324', 'department': 'Visual Effects', 'gender': 0, 'id': 1401789, 'job': 'Visual Effects Producer', 'name': 'Joyce Cox'}, {'credit_id': '5495994b92514132ed002951', 'department': 'Visual Effects', 'gender': 0, 'id': 1401790, 'job': 'Visual Effects Producer', 'name': 'Jenny Foster'}, {'credit_id': '549599cbc3a3686ae1004613', 'department': 'Crew', 'gender': 0, 'id': 1401791, 'job': 'Visual Effects Editor', 'name': 'Christopher Marino'}, {'credit_id': '549599f2c3a3686ae100461e', 'department': 'Crew', 'gender': 0, 'id': 1401792, 'job': 'Visual Effects Editor', 'name': 'Jim Milton'}, {'credit_id': '54959a51c3a3686af3003eb5', 'department': 'Visual Effects', 'gender': 0, 'id': 1401793, 'job': 'Visual Effects Producer', 'name': 'Cyndi Ochs'}, {'credit_id': '54959a7cc3a36811530026f4', 'department': 'Crew', 'gender': 0, 'id': 1401794, 'job': 'Visual Effects Editor', 'name': 'Lucas Putnam'}, {'credit_id': '54959b91c3a3680ff5002cb4', 'department': 'Visual Effects', 'gender': 0, 'id': 1401795, 'job': 'Visual Effects Supervisor', 'name': "Anthony 'Max' Ivins"}, {'credit_id': '54959bb69251412c4e002a5f', 'department': 'Visual Effects', 'gender': 0, 'id': 1401796, 'job': 'Visual Effects Supervisor', 'name': 'John Knoll'}, {'credit_id': '54959cbbc3a3686ae3004391', 'department': 'Visual Effects', 'gender': 2, 'id': 1401799, 'job': 'Visual Effects Supervisor', 'name': 'Eric Saindon'}, {'credit_id': '54959d06c3a3686ae90043f6', 'department': 'Visual Effects', 'gender': 0, 'id': 1401800, 'job': 'Visual Effects Supervisor', 'name': 'Wayne Stables'}, {'credit_id': '54959d259251416e1e003f11', 'department': 'Visual Effects', 'gender': 0, 'id': 1401801, 'job': 'Visual Effects Supervisor', 'name': 'David Stinnett'}, {'credit_id': '54959db49251413af7002975', 'department': 'Visual Effects', 'gender': 0, 'id': 1401803, 'job': 'Visual Effects Supervisor', 'name': 'Guy Williams'}, {'credit_id': '54959de4c3a3681153002750', 'department': 'Crew', 'gender': 0, 'id': 1401804, 'job': 'Stunt Coordinator', 'name': 'Stuart Thorp'}, {'credit_id': '54959ef2c3a3680fc60027f2', 'department': 'Lighting', 'gender': 0, 'id': 1401805, 'job': 'Best Boy Electric', 'name': 'Giles Coburn'}, {'credit_id': '54959f07c3a3680fc60027f9', 'department': 'Camera', 'gender': 2, 'id': 1401806, 'job': 'Still Photographer', 'name': 'Mark Fellman'}, {'credit_id': '54959f47c3a3681153002774', 'department': 'Lighting', 'gender': 0, 'id': 1401807, 'job': 'Lighting Technician', 'name': 'Scott Sprague'}, {'credit_id': '54959f8cc3a36831b8001df2', 'department': 'Visual Effects', 'gender': 0, 'id': 1401808, 'job': 'Animation Director', 'name': 'Jeremy Hollobon'}, {'credit_id': '54959fa0c3a36831b8001dfb', 'department': 'Visual Effects', 'gender': 0, 'id': 1401809, 'job': 'Animation Director', 'name': 'Orlando Meunier'}, {'credit_id': '54959fb6c3a3686af3003f54', 'department': 'Visual Effects', 'gender': 0, 'id': 1401810, 'job': 'Animation Director', 'name': 'Taisuke Tanimura'}, {'credit_id': '54959fd2c3a36831b8001e02', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 1401812, 'job': 'Set Costumer', 'name': 'Lilia Mishel Acevedo'}, {'credit_id': '54959ff9c3a3686ae300440c', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 1401814, 'job': 'Set Costumer', 'name': 'Alejandro M. Hernandez'}, {'credit_id': '5495a0ddc3a3686ae10046fe', 'department': 'Editing', 'gender': 0, 'id': 1401815, 'job': 'Digital Intermediate', 'name': 'Marvin Hall'}, {'credit_id': '5495a1f7c3a3686ae3004443', 'department': 'Production', 'gender': 0, 'id': 1401816, 'job': 'Publicist', 'name': 'Judy Alley'}, {'credit_id': '5592b29fc3a36869d100002f', 'department': 'Crew', 'gender': 0, 'id': 1418381, 'job': 'CG Supervisor', 'name': 'Mike Perry'}, {'credit_id': '5592b23a9251415df8001081', 'department': 'Crew', 'gender': 0, 'id': 1426854, 'job': 'CG Supervisor', 'name': 'Andrew Morley'}, {'credit_id': '55491e1192514104c40002d8', 'department': 'Art', 'gender': 0, 'id': 1438901, 'job': 'Conceptual Design', 'name': 'Seth Engstrom'}, {'credit_id': '5525d5809251417276002b06', 'department': 'Crew', 'gender': 0, 'id': 1447362, 'job': 'Visual Effects Art Director', 'name': 'Eric Oliver'}, {'credit_id': '554427ca925141586500312a', 'department': 'Visual Effects', 'gender': 0, 'id': 1447503, 'job': 'Modeling', 'name': 'Matsune Suzuki'}, {'credit_id': '551906889251415aab001c88', 'department': 'Art', 'gender': 0, 'id': 1447524, 'job': 'Art Department Manager', 'name': 'Paul Tobin'}, {'credit_id': '5592af8492514152cc0010de', 'department': 'Co

In [13]:
data['crew'] = data['crew'].apply(ast.literal_eval)

In [14]:
print(data['crew'][1])  ## crew를 리스트로 변환한 것 확인

[{'credit_id': '52fe4232c3a36847f800b579', 'department': 'Camera', 'gender': 2, 'id': 120, 'job': 'Director of Photography', 'name': 'Dariusz Wolski'}, {'credit_id': '52fe4232c3a36847f800b4fd', 'department': 'Directing', 'gender': 2, 'id': 1704, 'job': 'Director', 'name': 'Gore Verbinski'}, {'credit_id': '52fe4232c3a36847f800b54f', 'department': 'Production', 'gender': 2, 'id': 770, 'job': 'Producer', 'name': 'Jerry Bruckheimer'}, {'credit_id': '52fe4232c3a36847f800b503', 'department': 'Writing', 'gender': 2, 'id': 1705, 'job': 'Screenplay', 'name': 'Ted Elliott'}, {'credit_id': '52fe4232c3a36847f800b509', 'department': 'Writing', 'gender': 2, 'id': 1706, 'job': 'Screenplay', 'name': 'Terry Rossio'}, {'credit_id': '52fe4232c3a36847f800b57f', 'department': 'Editing', 'gender': 0, 'id': 1721, 'job': 'Editor', 'name': 'Stephen E. Rivkin'}, {'credit_id': '52fe4232c3a36847f800b585', 'department': 'Editing', 'gender': 2, 'id': 1722, 'job': 'Editor', 'name': 'Craig Wood'}, {'credit_id': '52fe4232c3a36847f800b573', 'department': 'Sound', 'gender': 2, 'id': 947, 'job': 'Original Music Composer', 'name': 'Hans Zimmer'}, {'credit_id': '52fe4232c3a36847f800b555', 'department': 'Production', 'gender': 2, 'id': 2444, 'job': 'Executive Producer', 'name': 'Mike Stenson'}, {'credit_id': '52fe4232c3a36847f800b561', 'department': 'Production', 'gender': 2, 'id': 2445, 'job': 'Producer', 'name': 'Eric McLeod'}, {'credit_id': '52fe4232c3a36847f800b55b', 'department': 'Production', 'gender': 2, 'id': 2446, 'job': 'Producer', 'name': 'Chad Oman'}, {'credit_id': '52fe4232c3a36847f800b567', 'department': 'Production', 'gender': 0, 'id': 2447, 'job': 'Producer', 'name': 'Peter Kohn'}, {'credit_id': '52fe4232c3a36847f800b56d', 'department': 'Production', 'gender': 0, 'id': 2448, 'job': 'Producer', 'name': 'Pat Sandston'}, {'credit_id': '52fe4232c3a36847f800b58b', 'department': 'Production', 'gender': 1, 'id': 2215, 'job': 'Casting', 'name': 'Denise Chamian'}, {'credit_id': '52fe4232c3a36847f800b597', 'department': 'Art', 'gender': 2, 'id': 1226, 'job': 'Production Design', 'name': 'Rick Heinrichs'}, {'credit_id': '52fe4232c3a36847f800b59d', 'department': 'Art', 'gender': 2, 'id': 553, 'job': 'Art Direction', 'name': 'John Dexter'}, {'credit_id': '52fe4232c3a36847f800b591', 'department': 'Production', 'gender': 1, 'id': 3311, 'job': 'Casting', 'name': 'Priscilla John'}, {'credit_id': '52fe4232c3a36847f800b5a3', 'department': 'Art', 'gender': 1, 'id': 4032, 'job': 'Set Decoration', 'name': 'Cheryl Carasik'}, {'credit_id': '52fe4232c3a36847f800b5a9', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 4033, 'job': 'Costume Design', 'name': 'Liz Dann'}, {'credit_id': '52fe4232c3a36847f800b5af', 'department': 'Costume & Make-Up', 'gender': 1, 'id': 4034, 'job': 'Costume Design', 'name': 'Penny Rose'}, {'credit_id': '56427ce8c3a3686a53000d8b', 'department': 'Sound', 'gender': 2, 'id': 5132, 'job': 'Music Supervisor', 'name': 'Bob Badami'}, {'credit_id': '55993c15c3a36855db002f33', 'department': 'Art', 'gender': 2, 'id': 146439, 'job': 'Conceptual Design', 'name': 'James Ward Byrkit'}, {'credit_id': '52fe4232c3a36847f800b5b9', 'department': 'Costume & Make-Up', 'gender': 1, 'id': 406204, 'job': 'Makeup Department Head', 'name': 'Ve Neill'}, {'credit_id': '56e47f7892514132690017bd', 'department': 'Crew', 'gender': 2, 'id': 1259516, 'job': 'Stunts', 'name': 'John Dixon'}, {'credit_id': '5740be639251416597000849', 'department': 'Crew', 'gender': 0, 'id': 1336716, 'job': 'CGI Supervisor', 'name': 'Dottie Starling'}, {'credit_id': '56427c639251412fc8000dc1', 'department': 'Directing', 'gender': 1, 'id': 1344278, 'job': 'Script Supervisor', 'name': 'Pamela Alch'}, {'credit_id': '57083101c3a3681d320004e6', 'department': 'Crew', 'gender': 0, 'id': 1368867, 'job': 'Special Effects Coordinator', 'name': 'Allen Hall'}, {'credit_id': '56427d5ec3a3686a62000d4a', 'department': 'Sound', 'gender': 0, 'id': 1368884, 'job': 'Music Editor', 'name': 'Melissa Muik'}, {'credit_id': '56427c7b9251412fd4000e07', 'department': 'Directing', 'gender': 1, 'id': 1395290, 'job': 'Script Supervisor', 'name': 'Sharron Reynolds'}, {'credit_id': '56427d2bc3a3686a53000d9b', 'department': 'Sound', 'gender': 0, 'id': 1399327, 'job': 'Music Editor', 'name': 'Barbara McDermott'}, {'credit_id': '56427cb4c3a3686a53000d87', 'department': 'Directing', 'gender': 1, 'id': 1400738, 'job': 'Script Supervisor', 'name': 'Karen Golden'}, {'credit_id': '56427d169251412fd4000e23', 'department': 'Sound', 'gender': 0, 'id': 1534197, 'job': 'Music Editor', 'name': 'Katie Greathouse'}]

In [15]:
def get_director(x):
    for i in x:
        if i['job'] == 'Director':
            return i['name']

In [16]:
get_director(data['crew'][0])

'James Cameron'

In [17]:
data['director'] = data['crew'].apply(get_director)

In [18]:
data.head()

,id,budget,genres,title,release_date,revenue,vote_average,vote_count,crew,cast,roi,director
0,19995,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,2009-12-10,2787965087,7.2,11800,"[{'credit_id': '52fe48009251416c750aca23', 'de...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",11.763566,James Cameron
1,285,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,2007-05-19,961000000,6.9,4500,"[{'credit_id': '52fe4232c3a36847f800b579', 'de...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",3.203333,Gore Verbinski
2,206647,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,2015-10-26,880674609,6.3,4466,"[{'credit_id': '54805967c3a36829b5002c41', 'de...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",3.594590,Sam Mendes
3,49026,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,2012-07-16,1084939099,7.6,9106,"[{'credit_id': '52fe4781c3a36847f81398c3', 'de...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",4.339756,Christopher Nolan
4,49529,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,2012-03-07,284139100,6.1,2124,"[{'credit_id': '52fe479ac3a36847f813eaa3', 'de...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",1.092843,Andrew Stanton

- 배우 컬럼 만들기

In [19]:
data['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [20]:
data['cast_name'] = data['cast'].apply(lambda x: [i['name'] for i in ast.literal_eval(x)])
data.head()

,id,budget,genres,title,release_date,revenue,vote_average,vote_count,crew,cast,roi,director,cast_name
0,19995,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,2009-12-10,2787965087,7.2,11800,"[{'credit_id': '52fe48009251416c750aca23', 'de...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",11.763566,James Cameron,"[Sam Worthington, Zoe Saldana, Sigourney Weave..."
1,285,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,2007-05-19,961000000,6.9,4500,"[{'credit_id': '52fe4232c3a36847f800b579', 'de...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",3.203333,Gore Verbinski,"[Johnny Depp, Orlando Bloom, Keira Knightley, ..."
2,206647,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,2015-10-26,880674609,6.3,4466,"[{'credit_id': '54805967c3a36829b5002c41', 'de...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",3.594590,Sam Mendes,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R..."
3,49026,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,2012-07-16,1084939099,7.6,9106,"[{'credit_id': '52fe4781c3a36847f81398c3', 'de...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",4.339756,Christopher Nolan,"[Christian Bale, Michael Caine, Gary Oldman, A..."
4,49529,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,2012-03-07,284139100,6.1,2124,"[{'credit_id': '52fe479ac3a36847f813eaa3', 'de...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",1.092843,Andrew Stanton,"[Taylor Kitsch, Lynn Collins, Samantha Morton,..."

- 장르 컬럼 만들기

In [21]:
data['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [22]:
data['genres'] = data['genres'].apply(ast.literal_eval)  ## genres도 리스트로 변환

In [23]:
def get_genres(x):
    if len(x) > 0:
        return x[0]['name']  ## 장르가 여러개일 경우 첫번째 장르만 가져오기

data['main_genre'] = data['genres'].apply(get_genres)
data.head()

,id,budget,genres,title,release_date,revenue,vote_average,vote_count,crew,cast,roi,director,cast_name,main_genre
0,19995,237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Avatar,2009-12-10,2787965087,7.2,11800,"[{'credit_id': '52fe48009251416c750aca23', 'de...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",11.763566,James Cameron,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",Action
1,285,300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Pirates of the Caribbean: At World's End,2007-05-19,961000000,6.9,4500,"[{'credit_id': '52fe4232c3a36847f800b579', 'de...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",3.203333,Gore Verbinski,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",Adventure
2,206647,245000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Spectre,2015-10-26,880674609,6.3,4466,"[{'credit_id': '54805967c3a36829b5002c41', 'de...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",3.594590,Sam Mendes,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",Action
3,49026,250000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",The Dark Knight Rises,2012-07-16,1084939099,7.6,9106,"[{'credit_id': '52fe4781c3a36847f81398c3', 'de...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",4.339756,Christopher Nolan,"[Christian Bale, Michael Caine, Gary Oldman, A...",Action
4,49529,260000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",John Carter,2012-03-07,284139100,6.1,2124,"[{'credit_id': '52fe479ac3a36847f813eaa3', 'de...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",1.092843,Andrew Stanton,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...",Action

- 데이터 타입 변경

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            4803 non-null   int64
 1   budget        4803 non-null   int64
 2   genres        4803 non-null   object
 3   title         4803 non-null   object
 4   release_date  4802 non-null   object
 5   revenue       4803 non-null   int64
 6   vote_average  4803 non-null   float64
 7   vote_count    4803 non-null   int64
 8   crew          4803 non-null   object
 9   cast          4803 non-null   object
 10  roi           3913 non-null   float64
 11  director      4773 non-null   object
 12  cast_name     4803 non-null   object
 13  main_genre    4775 non-null   object
dtypes: float64(2), int64(4), object(8)
memory usage: 525.5+ KB

In [25]:
data['release_date'] = pd.to_datetime(data['release_date'], format='%Y-%m-%d')
data['id'] = data['id'].astype(str)

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            4803 non-null   object
 1   budget        4803 non-null   int64
 2   genres        4803 non-null   object
 3   title         4803 non-null   object
 4   release_date  4802 non-null   datetime64[ns]
 5   revenue       4803 non-null   int64
 6   vote_average  4803 non-null   float64
 7   vote_count    4803 non-null   int64
 8   crew          4803 non-null   object
 9   cast          4803 non-null   object
 10  roi           3913 non-null   float64
 11  director      4773 non-null   object
 12  cast_name     4803 non-null   object
 13  main_genre    4775 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(3), object(8)
memory usage: 525.5+ KB

- 연도, 월 컬럼 만들기

In [27]:
data['year'] = data['release_date'].dt.year
data['month'] = data['release_date'].dt.month
data.head()

,id,budget,genres,title,release_date,revenue,vote_average,vote_count,crew,cast,roi,director,cast_name,main_genre,year,month
0,19995,237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Avatar,2009-12-10,2787965087,7.2,11800,"[{'credit_id': '52fe48009251416c750aca23', 'de...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",11.763566,James Cameron,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",Action,2009.0,12.0
1,285,300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Pirates of the Caribbean: At World's End,2007-05-19,961000000,6.9,4500,"[{'credit_id': '52fe4232c3a36847f800b579', 'de...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",3.203333,Gore Verbinski,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",Adventure,2007.0,5.0
2,206647,245000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Spectre,2015-10-26,880674609,6.3,4466,"[{'credit_id': '54805967c3a36829b5002c41', 'de...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",3.594590,Sam Mendes,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",Action,2015.0,10.0
3,49026,250000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",The Dark Knight Rises,2012-07-16,1084939099,7.6,9106,"[{'credit_id': '52fe4781c3a36847f81398c3', 'de...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",4.339756,Christopher Nolan,"[Christian Bale, Michael Caine, Gary Oldman, A...",Action,2012.0,7.0
4,49529,260000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",John Carter,2012-03-07,284139100,6.1,2124,"[{'credit_id': '52fe479ac3a36847f813eaa3', 'de...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",1.092843,Andrew Stanton,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...",Action,2012.0,3.0

- 결측치 제거

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            4803 non-null   object
 1   budget        4803 non-null   int64
 2   genres        4803 non-null   object
 3   title         4803 non-null   object
 4   release_date  4802 non-null   datetime64[ns]
 5   revenue       4803 non-null   int64
 6   vote_average  4803 non-null   float64
 7   vote_count    4803 non-null   int64
 8   crew          4803 non-null   object
 9   cast          4803 non-null   object
 10  roi           3913 non-null   float64
 11  director      4773 non-null   object
 12  cast_name     4803 non-null   object
 13  main_genre    4775 non-null   object
 14  year          4802 non-null   float64
 15  month         4802 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(3), object(8)
memory usage: 600.5+ KB

In [29]:
data.dropna(inplace=True)  ## 결측치 있는 모든 것 제거

- 데이터 확인

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3905 entries, 0 to 4799
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            3905 non-null   object
 1   budget        3905 non-null   int64
 2   genres        3905 non-null   object
 3   title         3905 non-null   object
 4   release_date  3905 non-null   datetime64[ns]
 5   revenue       3905 non-null   int64
 6   vote_average  3905 non-null   float64
 7   vote_count    3905 non-null   int64
 8   crew          3905 non-null   object
 9   cast          3905 non-null   object
 10  roi           3905 non-null   float64
 11  director      3905 non-null   object
 12  cast_name     3905 non-null   object
 13  main_genre    3905 non-null   object
 14  year          3905 non-null   float64
 15  month         3905 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(3), object(8)
memory usage: 518.6+ KB

In [31]:
data.head()

,id,budget,genres,title,release_date,revenue,vote_average,vote_count,crew,cast,roi,director,cast_name,main_genre,year,month
0,19995,237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Avatar,2009-12-10,2787965087,7.2,11800,"[{'credit_id': '52fe48009251416c750aca23', 'de...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",11.763566,James Cameron,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",Action,2009.0,12.0
1,285,300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Pirates of the Caribbean: At World's End,2007-05-19,961000000,6.9,4500,"[{'credit_id': '52fe4232c3a36847f800b579', 'de...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",3.203333,Gore Verbinski,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",Adventure,2007.0,5.0
2,206647,245000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Spectre,2015-10-26,880674609,6.3,4466,"[{'credit_id': '54805967c3a36829b5002c41', 'de...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",3.594590,Sam Mendes,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",Action,2015.0,10.0
3,49026,250000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",The Dark Knight Rises,2012-07-16,1084939099,7.6,9106,"[{'credit_id': '52fe4781c3a36847f81398c3', 'de...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",4.339756,Christopher Nolan,"[Christian Bale, Michael Caine, Gary Oldman, A...",Action,2012.0,7.0
4,49529,260000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",John Carter,2012-03-07,284139100,6.1,2124,"[{'credit_id': '52fe479ac3a36847f813eaa3', 'de...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",1.092843,Andrew Stanton,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...",Action,2012.0,3.0

## **분석**

### [1] 연도별 흥행 수익은?

In [32]:
import plotly.express as px

In [33]:
revenue_by_year = data.groupby('year')[['revenue']].sum().reset_index()

In [34]:
data.groupby('year')[['revenue']].sum().reset_index()

      year      revenue
0   1916.0      8394751
1   1925.0     22000000
2   1927.0       650422
3   1929.0      4358000
4   1930.0      8000000
..     ...          ...
84  2012.0  24141710246
85  2013.0  23411493295
86  2014.0  24120490589
87  2015.0  22775024221
88  2016.0  14461156948

[89 rows x 2 columns]

In [35]:
fig = px.line(data_frame=revenue_by_year, x="year", y="revenue")
fig.show()

In [36]:
data['release_date'].max()

Timestamp('2016-09-16 00:00:00')



> 2000년대에 들어 급격히 흥행 수익이 높아졌다.

### [2] 가장 흥행한 영화 TOP 10은?

In [37]:
top = data.groupby('title')['revenue'].sum().reset_index().sort_values('revenue', ascending=False).head(10)
fig = px.bar(data_frame=top, x='title', y='revenue', title=f"흥행 수익 TOP 10 영화")
fig.show()

- 예산 TOP 10, 투표수 TOP 10 영화는?

In [38]:
title_dic = {'budget':'예산', 'vote_count':'투표수'}
for y in ['budget','vote_count']:
    top = data.groupby('title')[[y]].sum().reset_index().sort_values(y, ascending=False).head(10)
    fig = px.bar(data_frame=top, x='title', y=y, title=f"{title_dic[y]} TOP 10 영화")
    fig.show()



> 대체적으로 예산, 투표수가 높으면 흥행 수익도 높아보이나, 정비례하진 않아 보인다. -> 상관관계 분석을 진행해보자.

### [3] 흥행에 가장 성공한 감독과 배우는?

- 가장 수익이 많은 감독, 배우는?

In [39]:
top_director = data.groupby(['director'])['revenue'].sum().reset_index().sort_values('revenue', ascending=False).head(10)
top_director

               director     revenue
1605   Steven Spielberg  9147393164
1317      Peter Jackson  6498642820
680       James Cameron  5883569439
1122        Michael Bay  5832524638
274   Christopher Nolan  4227483234
242      Chris Columbus  3725631503
1444    Robert Zemeckis  3590622002
567        George Lucas  3339113893
1657         Tim Burton  3337418241
1402       Ridley Scott  3189557997

In [40]:
top_director = data.groupby(['director'])['revenue'].sum().reset_index().sort_values('revenue', ascending=False).head(10)
fig = px.bar(data_frame=top_director, x='director', y='revenue', title=f"흥행 수익 TOP 10 감독")
fig.show()

In [41]:
revenue_cast = data[['revenue', 'cast_name']].explode('cast_name')  
## explode() 함수는 Pandas에서 사용하는 함수로, 리스트나 배열 형태의 값을 개별 행으로 분해해주는 기능을 합니다.

In [42]:
data[['revenue', 'cast_name']].explode('cast_name')

         revenue           cast_name
0     2787965087     Sam Worthington
0     2787965087         Zoe Saldana
0     2787965087    Sigourney Weaver
0     2787965087        Stephen Lang
0     2787965087  Michelle Rodriguez
...          ...                 ...
4799           0        Edward Burns
4799           0         Kerry Bishé
4799           0     Marsha Dietlein
4799           0  Caitlin Fitzgerald
4799           0     Daniella Pineda

[94990 rows x 2 columns]

In [43]:
top_cast = revenue_cast.groupby('cast_name')[['revenue']].sum().reset_index().sort_values('revenue', ascending=False).head(10)
fig = px.bar(data_frame=top_cast, x='cast_name', y='revenue', title=f"흥행 수익 TOP 10 배우")
fig.show()



> 유명 감독과 배우 일부가 많은 흥행 수익을 차지하고 있다.

### [4] 장르와 흥행 수익
- 흥행 수익이 좋은 장르는?
- 시간의 흐름에 따라 유행하는 장르가 바뀌는가?
- 월별로 흥행하는 장르가 있는가?

- 장르별 흥행 수익 분포

In [44]:
fig = px.box(data_frame = data, y = 'main_genre', x = 'revenue', hover_name = 'title')
fig.show()



> 액션과 드라마 장르에 흥행 수익이 아주 높은 영화들이 많이 있지만, 중앙값을 비교하면 다른 장르에 비해 높은 편은 아니다.

In [45]:
genre_avg_revenue = data.groupby('main_genre')[['revenue']].mean().reset_index()
genre_avg_revenue

         main_genre       revenue
0            Action  1.363256e+08
1         Adventure  2.277574e+08
2         Animation  2.753340e+08
3            Comedy  6.677665e+07
4             Crime  5.479147e+07
5       Documentary  1.557872e+07
6             Drama  5.843400e+07
7            Family  2.125577e+08
8           Fantasy  1.628720e+08
9           Foreign  1.113000e+05
10          History  8.663812e+07
11           Horror  5.491891e+07
12            Music  3.992297e+07
13          Mystery  8.877585e+07
14          Romance  8.104145e+07
15  Science Fiction  1.838426e+08
16         TV Movie  0.000000e+00
17         Thriller  7.822472e+07
18              War  7.396235e+07
19          Western  5.576662e+07

In [46]:
genre_avg_revenue = data.groupby('main_genre')[['revenue']].mean().reset_index()
fig = px.bar(data_frame = genre_avg_revenue, x = 'main_genre', y = 'revenue', title = '장르별 흥행 수익 평균')
fig.show()



> 장르별 영화 수익 평균은 애니메이션 > 어드벤쳐 > 가족 > SF > 판타지 > 액션 순이다.

In [47]:
genre_sum_revenue = data.groupby('main_genre')[['revenue']].sum().reset_index()
fig = px.bar(data_frame = genre_sum_revenue, x = 'main_genre', y = 'revenue', title = '장르별 흥행 수익 합계')
fig.show()



> 흥행 수익 합계는 액션 > 어드벤쳐 > 드라마 > 코미디 > 애니메이션 순이다.

- 연도별 장르별 수익

In [48]:
revenue_by_year_genre = data.query('year >= 1990').groupby(['year','main_genre'])[['revenue']].sum().reset_index()

In [49]:
fig = px.bar(data_frame=revenue_by_year_genre, x="year", y="revenue", color='main_genre', color_discrete_sequence=px.colors.qualitative.Light24_r)
fig.show()

In [61]:
pd.pivot_table(data=data.query('year>=1990'), index='year', columns='main_genre', values='revenue', aggfunc='sum', fill_value=0, margins=True, margins_name='All').reset_index().head(10)

main_genre,year,Action,Adventure,Animation,Comedy,Crime,Documentary,Drama,Family,Fantasy,...,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western,All
0,1990.0,769544404,930395890,0,788702323,136766062,0,160242857,0,558000000,...,0,0,0,463000000,57120318,0,0,0,0,3863771854
1,1991.0,582590848,691348731,0,128825902,512546991,0,317417844,0,0,...,226374459,0,0,0,174900000,0,30102717,0,0,2664107492
2,1992.0,364285917,321731527,504050219,693030895,25386235,0,537250262,0,149022650,...,32101000,121697323,0,278411639,159773545,0,411006745,0,159157447,3756905404
3,1993.0,424245126,1447858990,0,643712555,0,0,1222171004,2119994,15938065,...,0,0,0,100906973,0,0,0,25000000,0,3881952707
4,1994.0,1466077288,209007388,0,1392820924,0,7830611,388196413,788241776,625464565,...,241754789,0,0,373783407,120000000,0,315575343,0,0,5928752504
5,1995.0,2047258928,994088938,373554033,291349031,699017404,0,947556676,0,563347634,...,15116634,106269971,0,2122561,113374103,0,25405445,15000000,0,6207143123
6,1996.0,2811425901,570077268,250200000,802868789,588623357,0,1044431513,129832389,293664499,...,25836616,0,0,0,150000000,0,0,0,0,6808007511
7,1997.0,2585680633,1483283962,143370985,1407838209,417204103,0,2876320806,0,0,...,358579285,0,0,0,231370418,0,131097899,0,0,9634746300
8,1998.0,1798977791,980804494,409374083,1619204596,247091409,0,1507689664,0,181112600,...,334668408,16757163,237127149,739323110,131100000,0,19870567,0,0,8223101034
9,1999.0,1240186179,1790721773,888376806,1754543460,367539639,500000,1527872967,0,354407462,...,586644833,0,834897500,702466272,36450736,0,248133282,0,0,10332740909

In [65]:
revenue_by_year_genre_pct = pd.pivot_table(data=data.query('year >= 1990'), index='year', columns='main_genre', values='revenue', aggfunc=sum, fill_value=0, margins=True)
revenue_by_year_genre_pct = 100 * revenue_by_year_genre_pct.div(revenue_by_year_genre_pct.iloc[:,-1], axis=0).drop('All').drop('All', axis=1)
revenue_by_year_genre_pct

C:\Users\ryang\AppData\Local\Temp\ipykernel_10904\1083984807.py:1: FutureWarning:

The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.

C:\Users\ryang\AppData\Local\Temp\ipykernel_10904\1083984807.py:1: FutureWarning:

The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.

C:\Users\ryang\AppData\Local\Temp\ipykernel_10904\1083984807.py:1: FutureWarning:

The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.

main_genre,Action,Adventure,Animation,Comedy,Crime,Documentary,Drama,Family,Fantasy,Foreign,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
year,,,,,,,,,,,,,,,,,,,,
1990.0,19.916921,24.079990,0.000000,20.412756,3.539703,0.000000,4.147317,0.000000,14.441846,0.000000,0.000000,0.000000,0.000000,0.000000,11.983109,1.478356,0.0,0.000000,0.000000,0.000000
1991.0,21.868143,25.950482,0.000000,4.835612,19.238976,0.000000,11.914603,0.000000,0.000000,0.000000,0.000000,8.497197,0.000000,0.000000,0.000000,6.565050,0.0,1.129936,0.000000,0.000000
1992.0,9.696436,8.563738,13.416633,18.446855,0.675722,0.000000,14.300340,0.000000,3.966633,0.000000,0.000000,0.854453,3.239297,0.000000,7.410664,4.252797,0.0,10.940034,0.000000,4.236398
1993.0,10.928653,37.297183,0.000000,16.582184,0.000000,0.000000,31.483408,0.054612,0.410568,0.000000,0.000000,0.000000,0.000000,0.000000,2.599387,0.000000,0.0,0.000000,0.644006,0.000000
1994.0,24.728259,3.525318,0.000000,23.492647,0.000000,0.132079,6.547691,13.295238,10.549682,0.000000,0.000000,4.077667,0.000000,0.000000,6.304588,2.024035,0.0,5.322795,0.000000,0.000000
1995.0,32.982306,16.015241,6.018131,4.693770,11.261500,0.000000,15.265584,0.000000,9.075796,0.000000,0.220420,0.243536,1.712059,0.000000,0.034195,1.826510,0.0,0.409294,0.241657,0.000000
1996.0,41.295870,8.373629,3.675084,11.793007,8.646044,0.000000,15.341222,1.907054,4.313516,0.000000,2.071784,0.379503,0.000000,0.000000,0.000000,2.203288,0.0,0.000000,0.000000,0.000000
1997.0,26.837039,15.395153,1.488062,14.612094,4.330203,0.000000,29.853623,0.000000,0.000000,0.000000,0.000000,3.721730,0.000000,0.000000,0.000000,2.401417,0.0,1.360678,0.000000,0.000000
1998.0,21.877121,11.927428,4.978342,19.690924,3.004845,0.000000,18.334807,0.000000,2.202485,0.000000,0.000000,4.069856,0.203782,2.883671,8.990807,1.594289,0.0,0.241643,0.000000,0.000000
1999.0,12.002490,17.330559,8.597688,16.980426,3.557039,0.004839,14.786715,0.000000,3.429946,0.000000,0.000000,5.677534,0.000000,8.080116,6.798450,0.352769,0.0,2.401428,0.000000,0.000000
2000.0,18.746220,16.955374,6.038884,20.044093,3.275066,0.194194,15.777400,3.275112,2.947810,0.000000,0.000000,3.402917,0.000000,0.362695,0.334270,4.241574,0.0,4.404392,0.000000,0.000000
2001.0,17.703685,28.299550,5.643386,16.914276,1.963663,0.167983,13.558295,0.000000,2.081374,0.000000,3.385270,1.138682,0.128049,0.918470,0.000000,0.335051,0.0,7.031466,0.730800,0.000000
2002.0,17.877504,22.159587,3.621039,11.682681,4.364977,0.683421,18.293166,1.389742,7.868480,0.000000,0.000000,2.483562,0.000000,1.886745,1.177717,1.307624,0.0,4.160310,0.204538,0.838910
2003.0,17.539842,29.528222,7.098758,16.325770,1.318544,0.105884,13.456816,1.530454,5.344535,0.000000,0.000000,3.205183,0.054945,0.635110,0.440813,0.000000,0.0,2.934559,0.000000,0.480566
2004.0,23.004217,20.576757,4.989302,17.005693,0.083569,0.988136,16.527330,0.270855,2.995679,0.000000,0.000000,3.223977,0.404056,1.600709,0.851351,1.828459,0.0,3.799505,1.027713,0.822692
2005.0,15.616804,26.691208,4.324131,12.741358,2.935487,0.864894,15.782408,3.998249,0.826147,0.000000,0.004377,4.466819,0.000000,0.530301,3.042305,5.952946,0.0,2.222565,0.000000,0.000000
2006.0,12.286776,22.459247,11.467142,18.852678,2.135119,0.288063,15.397116,0.075176,4.026753,0.000000,0.000000,4.339720,0.895275,0.000000,2.045317,0.186766,0.0,5.113164,0.431688,0.000000
2007.0,11.073522,23.626318,7.881797,13.168977,4.781482,0.159140,12.457966,3.685392,11.873995,0.000000,0.339987,5.467545,0.137833,0.000000,0.106114,0.635103,0.0,4.180273,0.000000,0.424556
2008.0,15.270882,24.097381,5.966101,17.433164,0.704402,0.041437,18.869789,3.328122,7.184947,0.000000,0.300829,1.274823,0.831158,1.000805,1.203031,0.902225,0.0,1.478389,0.112517,0.000000
2009.0,26.095809,15.047792,13.004781,16.741665,0.456629,0.174838,8.813436,0.474961,2.514480,0.000000,1.016031,2.662058,0.000000,0.678927,2.166724,7.343657,0.0,2.808214,0.000000,0.000000
2010.0,19.623094,14.674905,13.093002,19.733810,1.646670,0.059214,14.968804,5.676333,3.771735,0.000000,0.000000,3.245728,0.000000,0.270074,0.421918,0.700814,0.0,1.647612,0.466288,0.000000
2011.0,28.730447,14.229903,13.993545,15.304439,1.621939,0.570896,10.062386,0.770007,2.418086,0.000000,0.560302,2.927509,0.000000,0.000000,1.929888,0.623346,0.0,6.257222,0.000085,0.000000
2012.0,25.790021,15.446026,11.166292,10.282512,1.856419,0.279254,11.264188,2.395697,2.290899,0.000461,1.180183,1.874870,0.581859,0.000000,0.633530,11.441873,0.0,3.515915,0.000000,0.000000
2013.0,29.340300,13.391224,17.880334,10.101137,2.684112,0.000000,8.515850,0.000000,5.065090,0.000000,0.000000,3.397788,0.104745,0.000000,0.864811,6.661598,0.0,1.993009,0.000000,0.000000
2014.0,28.612484,11.677908,3.653975,7.811740,1.734542,0.000000,7.299483,3.445776,6.552790,0.000000,1.267591,3.802688,0.279211,1.595231,1.738035,12.575144,0.0,4.105752,3.833377,0.014274
2015.0,40.401853,7.739941,4.551975,7.797515,2.119827,0.000000,15.069655,5.078945,2.553109,0.000000,0.000000,1.540984,0.000000,0.000000,3.257113,5.298237,0.0,2.250780,0.000000,2.340066
2016.0,46.806553,13.252491,6.057318,5.479643,0.106747,0.000000,2.937980,9.102523,4.810644,0.000000,0.000000,4.085717,0.000000,0.858377,0.874497,3.761350,0.0,1.693034,0.173125,0.000000

In [67]:
revenue_by_year_genre_pct = pd.pivot_table(data=data.query('year >= 1990'), index='year', columns='main_genre', values='revenue', aggfunc=sum, fill_value=0, margins=True)
revenue_by_year_genre_pct = 100 * revenue_by_year_genre_pct.div(revenue_by_year_genre_pct.iloc[:,-1], axis=0).drop('All').drop('All', axis=1)
revenue_by_year_genre_pct = pd.melt(revenue_by_year_genre_pct.reset_index(), id_vars='year', value_name='pct')
revenue_by_year_genre_pct

C:\Users\ryang\AppData\Local\Temp\ipykernel_10904\1265881647.py:1: FutureWarning:

The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.

C:\Users\ryang\AppData\Local\Temp\ipykernel_10904\1265881647.py:1: FutureWarning:

The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.

C:\Users\ryang\AppData\Local\Temp\ipykernel_10904\1265881647.py:1: FutureWarning:

The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.

       year main_genre        pct
0    1990.0     Action  19.916921
1    1991.0     Action  21.868143
2    1992.0     Action   9.696436
3    1993.0     Action  10.928653
4    1994.0     Action  24.728259
..      ...        ...        ...
535  2012.0    Western   0.000000
536  2013.0    Western   0.000000
537  2014.0    Western   0.014274
538  2015.0    Western   2.340066
539  2016.0    Western   0.000000

[540 rows x 3 columns]

In [68]:
fig = px.bar(data_frame=revenue_by_year_genre_pct, x="year", y="pct", color='main_genre', color_discrete_sequence=px.colors.qualitative.Light24_r)
fig.show()



> 2010년도부터 액션 영화의 흥행 수익 비중이 높아지기 시작했다.

> 1990년대 후반 ~ 2000년대 초반에는 드라마 장르의 흥행 수익이 높았다.

In [69]:
revenue_by_month_genre = data.query('year >= 1990').groupby(['month','main_genre'])[['revenue']].sum().reset_index()

In [70]:
fig = px.bar(data_frame=revenue_by_month_genre, x="month", y="revenue", color='main_genre', color_discrete_sequence=px.colors.qualitative.Light24_r)
fig.show()

In [71]:
revenue_by_month_genre_pct = pd.pivot_table(data=data.query('year >= 1990'), index='month', columns='main_genre', values='revenue', aggfunc=sum, fill_value=0, margins=True,)
revenue_by_month_genre_pct = 100 * revenue_by_month_genre_pct.div(revenue_by_month_genre_pct.iloc[:,-1], axis=0).drop('All').drop('All', axis=1)
revenue_by_month_genre_pct = pd.melt(revenue_by_month_genre_pct.reset_index(), id_vars='month', value_name='pct')
revenue_by_month_genre_pct

C:\Users\ryang\AppData\Local\Temp\ipykernel_10904\2880140727.py:1: FutureWarning:

The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.

C:\Users\ryang\AppData\Local\Temp\ipykernel_10904\2880140727.py:1: FutureWarning:

The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.

C:\Users\ryang\AppData\Local\Temp\ipykernel_10904\2880140727.py:1: FutureWarning:

The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.

     month main_genre        pct
0      1.0     Action  30.795424
1      2.0     Action  21.360752
2      3.0     Action  25.562012
3      4.0     Action  36.264242
4      5.0     Action  18.635487
..     ...        ...        ...
235    8.0    Western   1.042351
236    9.0    Western   0.316362
237   10.0    Western   0.000000
238   11.0    Western   0.000000
239   12.0    Western   1.171624

[240 rows x 3 columns]

In [72]:
fig = px.bar(data_frame=revenue_by_month_genre_pct, x="month", y="pct", color='main_genre', color_discrete_sequence=px.colors.qualitative.Light24_r)
fig.show()



> 액션, 어드벤처 장르는 비교적 봄, 여름에 개봉 수익이 높았다.

> 드라마 장르는 비교적 가을, 겨울에 개봉 수익이 높았다.

> 코미디 장르는 비교적 겨울에 개봉 수익이 높았다.

### [5] 수익과 예산, 투표수, 평점과의 상관관계는?

In [73]:
data[['budget','revenue','vote_average','vote_count']].corr()

                budget   revenue  vote_average  vote_count
budget        1.000000  0.710727      0.013522    0.560056
revenue       0.710727  1.000000      0.196757    0.768594
vote_average  0.013522  0.196757      1.000000    0.354340
vote_count    0.560056  0.768594      0.354340    1.000000

In [74]:
fig = px.imshow(data[['budget','revenue','vote_average','vote_count']].corr(), text_auto='.2f', color_continuous_scale='Purp')
fig.show()

In [75]:
for x in ['budget', 'vote_count', 'vote_average']:
    fig = px.scatter(data_frame = data, x = x, y = 'revenue', hover_name = 'title', size = 'revenue', color = 'revenue'
    , color_continuous_scale = px.colors.sequential.Sunsetdark, width = 700, height = 600, trendline = 'ols')
    fig.show()

- 흥행 수익 TOP 100 영화들만 필터링해서 본다면?

In [78]:
top100 = data.sort_values('revenue', ascending=False).head(100)
top100

,id,budget,genres,title,release_date,revenue,vote_average,vote_count,crew,cast,roi,director,cast_name,main_genre,year,month
0,19995,237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Avatar,2009-12-10,2787965087,7.2,11800,"[{'credit_id': '52fe48009251416c750aca23', 'de...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",11.763566,James Cameron,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",Action,2009.0,12.0
25,597,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",Titanic,1997-11-18,1845034188,7.5,7562,"[{'credit_id': '52fe425ac3a36847f8017985', 'de...","[{""cast_id"": 20, ""character"": ""Rose DeWitt Buk...",9.225171,James Cameron,"[Kate Winslet, Leonardo DiCaprio, Frances Fish...",Drama,1997.0,11.0
16,24428,220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",The Avengers,2012-04-25,1519557910,7.4,11776,"[{'credit_id': '52fe4495c3a368484e02b1cf', 'de...","[{""cast_id"": 46, ""character"": ""Tony Stark / Ir...",6.907081,Joss Whedon,"[Robert Downey Jr., Chris Evans, Mark Ruffalo,...",Science Fiction,2012.0,4.0
28,135397,150000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Jurassic World,2015-06-09,1513528810,6.5,8662,"[{'credit_id': '52fe4bf7c3a368484e1a0683', 'de...","[{""cast_id"": 10, ""character"": ""Owen Grady"", ""c...",10.090192,Colin Trevorrow,"[Chris Pratt, Bryce Dallas Howard, Irrfan Khan...",Action,2015.0,6.0
44,168259,190000000,"[{'id': 28, 'name': 'Action'}]",Furious 7,2015-04-01,1506249360,7.3,4176,"[{'credit_id': '52fe4cc8c3a36847f823e699', 'de...","[{""cast_id"": 17, ""character"": ""Dominic Toretto...",7.927628,James Wan,"[Vin Diesel, Paul Walker, Dwayne Johnson, Mich...",Action,2015.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,9806,92000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",The Incredibles,2004-11-05,631442092,7.4,5152,"[{'credit_id': '52fe4531c3a36847f80c159d', 'de...","[{""cast_id"": 1, ""character"": ""Bob Parr / Mr. I...",6.863501,Brad Bird,"[Craig T. Nelson, Holly Hunter, Samuel L. Jack...",Action,2004.0,11.0
270,286217,108000000,"[{'id': 18, 'name': 'Drama'}, {'id': 12, 'name...",The Martian,2015-09-30,630161890,7.6,7268,"[{'credit_id': '5607a7e19251413050003e2c', 'de...","[{""cast_id"": 0, ""character"": ""Mark Watney"", ""c...",5.834832,Ridley Scott,"[Matt Damon, Jessica Chastain, Kristen Wiig, J...",Drama,2015.0,9.0
204,51497,125000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",Fast Five,2011-04-20,626137675,7.1,2438,"[{'credit_id': '52fe47f6c3a36847f8151b0f', 'de...","[{""cast_id"": 2, ""character"": ""Dominic Toretto""...",5.009101,Justin Lin,"[Vin Diesel, Paul Walker, Jordana Brewster, Ty...",Action,2011.0,4.0
115,8960,150000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'na...",Hancock,2008-07-01,624029371,6.2,2961,"[{'credit_id': '52fe44cbc3a36847f80aa60f', 'de...","[{""cast_id"": 2, ""character"": ""John Hancock"", ""...",4.160196,Peter Berg,"[Will Smith, Charlize Theron, Jason Bateman, J...",Fantasy,2008.0,7.0
18,41154,225000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",Men in Black 3,2012-05-23,624026776,6.2,4160,"[{'credit_id': '52fe45b7c3a36847f80d68c7', 'de...","[{""cast_id"": 4, ""character"": ""Agent J"", ""credi...",2.773452,Barry Sonnenfeld,"[Will Smith, Tommy Lee Jones, Josh Brolin, Mic...",Action,2012.0,5.0

In [76]:
top100 = data.sort_values('revenue', ascending=False).head(100)

fig = px.imshow(top100[['budget','revenue','vote_average','vote_count']].corr(), text_auto='.2f', color_continuous_scale='Mint')
fig.show()

In [79]:
for x in ['budget', 'vote_count', 'vote_average']:
    fig = px.scatter(data_frame = top100, x = x, y = 'revenue', hover_name = 'title', size = 'revenue', color = 'revenue'
    , color_continuous_scale = px.colors.sequential.Emrld, width = 700, height = 600, trendline = 'ols', trendline_color_override='green')
    fig.show()



> 예산과 투표수는 흥행 수익과 높은 양의 상관관계를 보이나, 평점 평균은 비교적 낮은 양의 상관관계를 보인다.

> 흥행에 성공한 영화 상위 100개로 추려보면, 그 상관관계가 더 낮아진다.

### [6] ROI(예산 대비 수익)가 높으면서 흥행에 성공한 영화의 특징은?

In [80]:
top300 = data.sort_values('revenue', ascending=False).head(300)

fig = px.scatter(data_frame = top300, x = 'roi', y = 'revenue', hover_name = 'title', size = 'revenue', color = 'main_genre',
color_discrete_sequence=px.colors.qualitative.Light24, width = 700, height = 600)
fig.show()

In [81]:
fig = px.box(data_frame = top300, y = 'main_genre', x = 'roi', hover_name = 'title')
fig.show()



> 액션의 경우 예산이 큰 영화가 많아 ROI가 높은 편은 아니고, 드라마/코미디/로맨스 영화가 ROI가 큰 영화들이 많다.

## **정리**



> 2000년대에 들어 급격히 흥행 수익이 높아졌다.



> 유명 감독과 배우 일부가 많은 흥행 수익을 차지하고 있다.



> 액션과 드라마 장르에 흥행 수익이 아주 높은 영화들이 많이 있지만, 중앙값을 비교하면 다른 장르에 비해 높은 편은 아니다.

> 장르별 영화 수익 평균은 애니메이션 > 어드벤쳐 > 가족 > SF > 판타지 > 액션 순이다.

> 흥행 수익 합계는 액션 > 어드벤쳐 > 드라마 > 코미디 > 애니메이션 순이다.



> 2010년도부터 액션 영화의 흥행 수익 비중이 높아지기 시작했다.

> 1990년대 후반 ~ 2000년대 초반에는 드라마 장르의 흥행 수익이 높았다.

> 액션, 어드벤처 장르는 비교적 봄, 여름에 개봉 수익이 높았다.

> 드라마 장르는 비교적 가을, 겨울에 개봉 수익이 높았다.

> 코미디 장르는 비교적 겨울에 개봉 수익이 높았다.




> 예산과 투표수는 흥행 수익과 높은 양의 상관관계를 보이나, 평점 평균은 비교적 낮은 양의 상관관계를 보인다.

> 흥행에 성공한 영화 상위 100개로 추려보면, 그 상관관계가 더 낮아진다.



> 액션의 경우 예산이 큰 영화가 많아 ROI가 높은 편은 아니고, 드라마/코미디/로맨스 영화가 ROI가 큰 영화들이 많다.